### ISSUE TITLE
Zero width channel/server list

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1041]
**Reported by robm on 10 Dec 2010 22:40:51 UTC**
The server/channel list in tree view/mode has a minimum width.
I'd like to be able to set it to width=0 in order to use the maximum
possible width for the real important stuff which is the text in the channels.

Preferrably this option should be settable in the option dialog so users wouldn't have to do it on each programm start.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1041

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 12 Dec 2010 02:10:44**
Version: 4.0.2 Insomnia → 4.1 Equilibrium

**Comment by un1versal** [comment]
Please use Classic Window list, in 4.9.2 you can also Press **`Ctrl+T`** to alternate between tree window list and classic list.

The classic window list is by default set at bottom of client under Input line. so you get 100% width for the **important stuff**

Allowing 0 width isn't a great idea imo when there's good working alternatives. Bringing it back from 0 would be cumbersome to say the least since you need to go back into theme settings and apply some width other than 0.

closed as **wont fix** since this has been here since 2010 and noone doesnt have any interest on this either.
