### ISSUE TITLE
Optional setting to wait for NickServ auth before entering channels

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1101]
**Reported by g4borg on 28 Feb 2011 17:24:46 UTC**
Simple problem on freenode and e.g. the django channel, which tells you the following at login:

[18:14:39] Tipp für #django: Cannot join channel (+r) - you need to be identified with services

Well, however services identification only occurs a second later.

This way, the channel does not even get displayed in the channel list, and you have to manually enter /j django

Also, for me, clicking on #django in the log opens a new channel (???) where I am admin, which is weird but something different.

A nice feature would be to set the server or the channels individually for only being joined, if a nickserv auth was already successful.

This might also be a nice feature for other reasons (like security)

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1101

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 05 Mar 2011 11:03:28**
How do you identify to nickserv? On freenode, i suggest you to use sasl authentication

---

Version: none → 4.1 Equilibrium

**Comment by un1versal** [comment]
freenode sasl takes care of this. since this problem is reported against freenode and has a solution and is fully working Ill close this.

However indeed on networks that dont support sasl and where a bouncer isnt an option I can see value in this being a default behaviour (channels that you can only join if authed) rather than optional, ~~please reopen request as the latter if its desired.~~

**Comment by un1versal** [comment]
Reopened for @blindsighttf2

**Comment by ganego** [comment]
For people who might come here through google or whatever and have the same problem:

I use this script for the Event "OnNickServNotice":

```
if ($str.contains($3, "You are now identified")) {
    join #python }
```

EDIT: Thank you for the edit, I couldn't figure out how to format it properly.

Maybe you also want to add if ($context.networkName == "freenode") { } to check for the network if you use more than one.

Running a join script under the "OnNickServAuth" didn't work when I tried.

**Comment by ghost** [comment]
As far as I know, the `OnNickServAuth` only works if your ircd is registered with a `KviBasicIrcServerInfo` and has a value returned from `getRegisterModeChar()`.  Unfortunately, not all of the registered ircd's in KVIrc have a value set for this and not all ircd's out there are registered with KVIrc.

The best way to handle this would probably be a script, since an option in the channels auto-join dialog would probably use the same method and be just as unreliable as the `OnNickServAuth` method.  You'd end up with having to write an `OnNickServNotice` script like ganego suggested with checking for the NickServ response after you identify. Another unfortunate thing is that I've seen many different responses and in many languages when identifying, so keeping an updated list built-in to KVIrc would be a pain at best.

To have this "feature" work reliably, I think it's only available in a custom script.

**Comment by staticfox** [comment]
There isn't a uniform way to fix this, and adding in an "official" version would give the implication that they can successfully rely on such a method to ensure they are authed before they login. Which cannot be true for some cases. Closing, maybe someone can toss a custom script in to our script repo or something.

**Comment by un1versal** [comment]
@OmegaPhil youre the resident scripting expert, is there anything you can do?

**Comment by OmegaPhil** [comment]
I use [KVIrc NickServ Integration Script](https://github.com/OmegaPhil/kvirc-nickserv-integration-script) to manage identing etc - I got around this joining problem by leaving the normal autojoining apparatus alone, and unbanning/triggering autojoin with password submission as appropriate etc after authentication is acknowledged via OnNickServNotice. [Comments at the bottom of the script](https://github.com/OmegaPhil/kvirc-nickserv-integration-script/blob/master/NickServ%20Integration%20Script.kvs#L982) detail the steps it takes/stuff it really does.

Currently I'm the only user, so it just covers the networks I use - I'm happy to receive issues etc from other users if it doesn't work on their network, although it won't be worked on in the near future.

**Comment by un1versal** [comment]
Im assigning myself so I can have a look at this later
