### ISSUE TITLE
Crash when using perl

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1105]
**Reported by wodim on 08 Mar 2011 16:12:55 UTC**

```
panic: MUTEX_LOCK (22) [op.c:476] at (eval 1) line 3.
panic: MUTEX_LOCK (22) [op.c:476].

Program exited with code 0377.
```

It doesn't always crash, it does after using this script several times along a long time (~1 hour?):

```
perl.begin -f

use XML::Simple;
use LWP::Simple;

my $xml = new XML::Simple;
my $content = get("http://ws.audioscrobbler.com/1.0/user/egns/recenttracks.rss");

if(!$content) {
    KVIrc::eval("ECHO Could not retrieve your last tracks.");
} else {
    my $rss = $xml->XMLin($content);
    my $title = $rss->{channel}->{item}[0]->{title};
    KVIrc::eval("ME > $title");
}

perl.end
```

perl 5.12.3-1<br/>kvirc r5553<br/>x86_64

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1105

**Comment by DarthGandalf** [comment]
**Modified by wodim on 08 Mar 2011 16:21:22**
Version: none → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 13 Mar 2011 19:11:37**
I first thought as LWP being the culprit of a locking problem, so i modified your script to fetch the http page using kvs:

```
%RecentTracks_tmpfile = $file.localdir("tmp/recenttracks.rss");

http.asyncGet -c -e=o -w=h ("http://ws.audioscrobbler.com/1.0/user/egns/recenttracks.rss", %RecentTracks_tmpfile)
{
    %recenttracks = $file.read(%RecentTracks_tmpfile);

    perl.begin -f

    use XML::Simple;

    my $xml = new XML::Simple;
    my $content = KVIrc::getLocal("recenttracks");

    if(!$content) {
        KVIrc::eval("ECHO Could not retrieve your last tracks.");
    } else {
        my $rss = $xml->XMLin($content);
        my $title = $rss->{channel}->{item}[0]->{title};
        KVIrc::eval("ME > $title");
    }

    perl.end
}
```

Guess what? it crashed anyway after some time:

```
panic: MUTEX_LOCK (22) [op.c:476] at (eval 1) line 3.
panic: MUTEX_LOCK (22) [op.c:476].
```

I'll further investigate if the problem is somewhat related to XML::Simple or more generic.

---

Owner: pragmaware → ctrlaltca
Status: new → assigned

**Comment by pragmaware** [comment]
It croaks because a pthread_mutex_lock() call returns error 22 (EINVAL).
Does it happen also with recent perl versions?

**Comment by ghost** [comment]
```
panic: MUTEX_LOCK (22) [op.c:727] at (eval 1) line 3.
panic: MUTEX_LOCK (22) [op.c:727].
```

Yup, still there.  Took me running a script using LWP several times before it crashed.

**Comment by un1versal** [comment]
Some tweety bird told me this is likely related to Perl.

> `[05:08:33]  <Pragma> #1105 is probably a perl issue`

**Comment by ctrlaltca** [comment]
The problem here is that we call `PERL_SYS_INIT3(...)` every time the perlcore module is loaded and `PERL_SYS_TERM()` every time the module is unloaded.
From the [perlembed docs](http://perldoc.perl.org/perlembed.html):

> The macros PERL_SYS_INIT3() and PERL_SYS_TERM() provide system-specific tune up of the C runtime environment necessary to run Perl interpreters; they should only be called once regardless of how many interpreters you create or destroy. Call PERL_SYS_INIT3() before you create your first interpreter, and PERL_SYS_TERM() after you free your last interpreter.

So here what happens: the first time you run a perl script the module gets loaded and `PERL_SYS_INIT3()` called. The perl module will work fine until it gets automatically unloaded when no perl script is running since a few time.
Then, the next time you execute a perl script again, the perlcore module will be loaded again, causing `PERL_SYS_INIT3()` to be called again. Bad timing and bad luck, you'll get your perl panic.

The solution here is either to:
 * never unload the perlcore module, aka `perlcore_module_can_unload` always returning false, or
 * use a persistent (global?) variable to mark if the perlcore module has ever been loaded before and skip the `PERL_SYS_INIT3()` call.

Also, `PERL_SYS_TERM()` should only be called just before `exit()`, not every time the module gets unloaded.

**Comment by IceN9ne** [comment]
Good catch @ctrlaltca.  I changed the return value of `perlcore_module_can_unload` in the `perlcore` module to `false` and it indeed no longer crashes on scripts I previously could crash KVIrc with.

I'm in favor of using this method as I don't see a good reason to unload the `perlcore` module once it's been loaded.

**Comment by ctrlaltca** [comment]
> I'm in favor of using this method as I don't see a good reason to unload the perlcore module once it's been loaded.

Pushed as PR #2186
