### ISSUE TITLE
Scriptable function to display images inline

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1129]
**Reported by Gallion on 11 Apr 2011 11:55:47 UTC**
It would be nice to have a scriptable function to display images inline the same way emoticons are displayed, without a limit on the image size.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1129

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 11 Apr 2011 16:01:39**
this has to be discussed a bit...

---

Version: 4.0.4 Insomnia → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Comment by Sammy1Am on 25 Nov 2012 09:17:19**
Any update on this feature?  I don't know any C++, but is there anything I (we, the community) can do to help?

**Comment by un1versal** [comment]
Im thinking aloud here,  e.g. use case would be to display a screenshot or something like that, but lets imagine you have a screenshot 1920x1080 there has to be a limit on size to be decided by size of KVIrc window, if your screen is 1920x1080 and KVIrc is taking 1000x900 how would that look?

Can you now imagine those users with screens that are still below HD resolutions, ouch...

So +1 with some really really really smart window size/monitor resolution detection and max limits behind else, I see this as becoming a huge no,no.

**Comment by un1versal** [comment]
the more I think about this the more I think its a terrible idea for the reasons I mentioned above, and since no one else is jumping to implement this or provide feedback I unilaterally voted to close this as wontfix

If someone who for their own reason thinks this is worthwhile idea, then feel free to reopen and relabel and state reasons for doing so.
