### ISSUE TITLE
wrong label for multiline editor in OS X

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1345]
**Reported by darkweasel on 04 Dec 2012 22:36:37 UTC**
On OS X, if you enter the multiline editor via option-enter, KVIrc will (at least in the German-language translation) display a message saying that Ctrl-Enter will send the message. However, in fact, on OS X, Cmd-Enter is the command to send a message from the multiline editor.

The line should be changed to display Cmd-Enter instead of Ctrl-Enter.

(It would actually be even better to use something like ⌥⌤ instead of alt-enter and ⌘⌤ instead of cmd-enter, which is what OS X users are accustomed to seeing in menus and the like.)

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1345

**Comment by un1versal** [comment]
Question, are the translations or kvirc shortcuts OS aware?

**Comment by un1versal** [comment]
Right this seems to be a widespread issue not just in this case.@wodim

What I suggest is that part of #1704 which would require something like making the shortcuts be OS aware in all instances instead of shortcuts being hardcoded as part of string... (this is ideal and only acceptable solution imo) but other suggestions welcome.

**We cant and should not** add OSX specific strings either, that read exactly like the Linux/Windows strings (**because the wording has to be exact same with exception of shortcuts in all OS**) and **#ifdef** them out, **because that would cause a unreasonable amount of translation work** due to sheer amount of instances. -- so if that's what the only option is I vote no.

**Comment by DarthGandalf** [comment]
I agree, substituting the key after the translation, via e.g. `%1` would be better.

**Comment by TheReign** [comment]
Check if this changes your opinion on this topic with PR #1800.

**Comment by wodim** [comment]
This was done already with 88178bf
