### ISSUE TITLE
Remember the size of the Servers (Ctrl + S) window

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1355]
**Reported by Visitor_099 on 04 Feb 2013 03:31:37 UTC**
Because the default is too damn small, it feels cramped in there.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1355

**Comment by un1versal** [comment]
Remembering sizes, this seems to be a general problem (know long standing bug), but the minimum size can be improved.

**Comment by un1versal** [comment]
sadly https://github.com/kvirc/KVIrc/commit/e2f8e3d28351e83a0ea5cd5d185550ed41770509 solutions wasnt fantastic since this dialog also opens inside general preferences

![wide prefs](https://lh3.googleusercontent.com/-wuMaX_ATNDs/V3VOUK4ICXI/AAAAAAABA9o/OA5C7Uphno0/s0/2016-06-30_18-52-30.png)

so best we can do here the way things are is to increase the minimum height of dialog a bit without making things look too odd... But I noticed that on windows the server dialog opens well off center and Im unsure if its related to this since https://github.com/kvirc/KVIrc/blob/master/src/kvirc/ui/KviMainWindow.cpp#L171-L174 comes into play...

If anyone has better solution without recoding the lot, fell free to submit a better alternative.
