### ISSUE TITLE
Emoticons don't show instead of text

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1364]
**Reported by soonce on 18 Feb 2013 22:31:32 UTC**
There are no graphics for text emoticons, "draw some emoticons as pictures" is selected, but there are no images for them under IRC > Tools > Text icons and if manually added, they dissapear on next start of the program.

KVIrc 4.2.0 svn-6190 'Equilibrium' 20120701 - build 2012-07-04 14:48:08 UTC

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1364

**Comment by DarthGandalf** [comment]
**Modified by wodim on 22 Mar 2013 23:15:50**
Priority: Crash → Normal

**Comment by un1versal** [comment]
This is probably fixed, never seen this happen currently.

**Comment by un1versal** [comment]
For the part where icons disappear....

This was probably reported against an internal theme (and is fully duplicable if tested against any internal theme), which in Linux resides in a non user writeable path not sure how that works for so when you add icons to this, a texticons.kvc should be created in user config but that doesnt happen at all.

I noticed this bug when adding more texticons in list and only managed to fix it by saving the theme to a different version and presto the texicons.kvc was created inside the theme directory.

IMO if internal theme then texticons.kvc should be written to and read from the user config folder. Currently its not read from there either :)

To the no images for text... I created https://github.com/kvirc/KVIrc/issues/1614, Im not marking that  as a duplicate of this but will reference it because there are two reports in this issue.
Both confirmed in current dev

**Comment by un1versal** [comment]
**Reported by gamer1990 on 10 Oct 2011 07:31:23 UTC**
The Graphics for Emoticons like ":D :)" and so on, are gone after Client-Restart, reset the Emoticons over the Settings fix this problem, but after a restart the Graphics are gone again.

KVIrc Equilibrium 4.1.3, revision: 5980, sources date: 20110830, built on: 2011-10-05 09:15:52 UTC

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1224
merged from Emoticons gone after Client Restart #1224

**Comment by pragmaware** [comment]
Probably no longer applicable (?).
