### ISSUE TITLE
Downloading 5 GB or larger file doesn't complete.  Stops at 100%.  End of file corrupted.

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1447]
**Reported by Aaron on 24 Dec 2013 19:32:51 UTC**
I've ran into this multiple times.  The file will stop downloading at 100%, there are a few megabytes (give or take) missing from the end and Process Explorer shows KVIrc using around 24% CPU at this point.  It will sit like this for hours until I abort the download, and the file never completely downloads.  KVIrc doesn't lock up.  I can still use it while all of this is going on.  I've tried aborting and resuming multiple times and rarely I can get it to say complete but a hash check of the file shows it is corrupted, probably at the end.

I am using the Windows 64 bit build available at http://kvirc.d00p.de/

I found this site in the announce message on your IRC channel.

I am using KVIrc v4.3.1 r6366.

If I had a debug build, I might be able to help track it down to see what thread it is running circles in since it never actually crashes.

I have a pretty clean Windows 7 install and the file seems to download alright with mIRC but that client doesn't support SSL DCC transfers without a inefficient hack.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1447

**Comment by un1versal** [comment]
Workaround is comment https://github.com/kvirc/KVIrc/blob/master/src/modules/dcc/DccFileTransfer.cpp#L406

See #1506 its a workaround buggy servers is only solution I found client side.

**Comment by un1versal** [comment]
[Not fixed](https://github.com/kvirc/KVIrc/pull/1506#issuecomment-139057368) please reopen.

**Comment by un1versal** [comment]
An alternative would be to implement #1447 as a selectable option and label it something like:

"Workaround buggy DCC servers"

With some setting description of:

"For large DCC transfers under certain server conditions the transfer doesn't complete and is corrupt, enabling this setting is workaround these servers by not sending an ACK, However this breaks the protocol, If you understand the consequences enable the option at your own peril."

Or something better.

**Comment by TheReign** [comment]
It's not specified in the original issue, but I'm going to assume that the user is attempting to download from iroffer or an mirc client.  This is a common issue that I've seen among non-mIRC users.  From my testing, it appears to be an issue where iroffer chose to follow the mIRC method and use 64-bit acks for files larger than 4GiB.  However, I can't find any client besides mIRC that actually sends 64-bit acks by default.

It culminates in the fact that iroffer assumes that it will receive a 64-bit ack (it does have 32-bit ack detection, but it's poor at best) and when iroffer gets to the end of the file, the acks don't match up and it makes some decision that the transfer is done and closes the socket before all of the data has been sent.

The best thing that can happen is for mIRC/iroffer to use 32-bit acks, but that's not going to happen.

The workaround that I've used in the past is to just not send acks for files larger than 4GiB, but this breaks the protocol and is not the best solution.

I think the best option that KVIrc can do is to create an option in the DCC file transfer options to send 64-bit acks on files larger than 4GiB.

Patch: http://pastebin.com/p4kHLi1s

This patch adds an option in "DCC > File Transfer > Advanced > Bug Compatibility" that will enable the usage of 64-bit acks when the file is larger than 4GiB.

I haven't tested this extensively, but it's worked so far.  Unfortunately, when dealing with files larger than 4GiB on a slow connection can cause testing to be rather slow and this issue doesn't happen 100% of the time, since in my experience it will randomly succeed sometimes with the standard 32-bit ack protocol.

Note: This partially reverts the bTolerateErrors workaround introduced in dc6c4f5 since it doesn't seem to do what was intended.

**Comment by TheReign** [comment]
It's not specified in the original issue, but I'm going to assume that the user is attempting to download from iroffer or an mirc client.  This is a common issue that I've seen among non-mIRC users.  From my testing, it appears to be an issue where iroffer chose to follow the mIRC method and use 64-bit acks for files larger than 4GiB.  However, I can't find any client besides mIRC that actually sends 64-bit acks by default.

It culminates in the fact that iroffer assumes that it will receive a 64-bit ack (it does have 32-bit ack detection, but it's poor at best) and when iroffer gets to the end of the file, the acks don't match up and it makes some decision that the transfer is done and closes the socket before all of the data has been sent.

The best thing that can happen is for mIRC/iroffer to use 32-bit acks, but that's not going to happen.

The workaround that I've used in the past is to just not send acks for files larger than 4GiB, but this breaks the protocol and is not the best solution.

I think the best option that KVIrc can do is to create an option in the DCC file transfer options to send 64-bit acks on files larger than 4GiB.

Patch: http://pastebin.com/p4kHLi1s

This patch adds an option in "DCC > File Transfer > Advanced > Bug Compatibility" that will enable the usage of 64-bit acks when the file is larger than 4GiB.

I haven't tested this extensively, but it's worked so far.  Unfortunately, when dealing with files larger than 4GiB on a slow connection can cause testing to be rather slow and this issue doesn't happen 100% of the time, since in my experience it will randomly succeed sometimes with the standard 32-bit ack protocol.

Note: This partially reverts the bTolerateErrors workaround introduced in dc6c4f5 since it doesn't seem to do what was intended.

**Comment by un1versal** [comment]
https://github.com/kvirc/KVIrc/issues/1755 should fix this... closing 2nd time lucky fingers crossed.
