### ISSUE TITLE
Global application font doesn't apply to input field

### ISSUE THREAD

**Issue by ekolis** [kvirc/KVIrc#1512]
I set the global application font to 9 point Arial, but the input field remains set to 12 point Arial; I have to change that separately.

**Comment by DarthGandalf** [comment]
Any details about your OS?

**Comment by ekolis** [comment]
Windows 10, though I seem to recall it happening on Windows 8 as well.

**Comment by un1versal** [comment]
Is this a bug though? I dont think so, to me global application font type and size, is not in the sense of global everywhere, its poorly named perhaps, BUt to me it implies for application wide visible text outside of input/ouput areas, like settings and button text, dialog text etc.

Lets see this from another angle, you have specific settings for input/output to set font type and size, if these were overridden by this gobal, then how can you justify having specific settings that are disconnected from this? For that scenario to work best imo you'd need to disable the specific input/output and other areas font settings so that when global is defined global rules and imo that wouldnt work well and you need to tweak font sizes to best suit other areas separately.

If on other hand you change change the font everywhere when global is applied and still allow specific area changes then the purpose is defeated of having global take over imo.

imo what needs here is specifying exactly what global means by tootip or note text on dialog, perhaps even rename it to **Application dialogs font settings** instead.

**Comment by un1versal** [comment]
@TheReign @wodim @everyoneelse thoughts?

**Comment by un1versal** [comment]
thoughts anyone?

**Comment by ctrlaltca** [comment]
The global application font is the default font used for everything that doesn't have a specific font option.
It doesn't override/disable the font options of the specific widgets that have one.

**Comment by un1versal** [comment]
so this ticket is invalid then as that's expected behavior, seems to work fine in Linux near as I can tell.

@ekolis can you confirm this still happens?

In 7 days will close this with no reply we can reopen later if needed

**Comment by un1versal** [comment]
7 days passed and then some. if this is still an issue please reopen.
