### ISSUE TITLE
cmake: Support for uninstall global files/direcories

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1551]
See https://github.com/kvirc/KVIrc/blob/master/doc/TODO-cmake

This request is to mirror that todo list, and I obviously think its a must for any app that you can compile.

You cant uninstall a compiled KVIrc instance in Linux without this.

**Comment by un1versal** [comment]
This is really required now in Linux to work the same manner that the Windows installer detects previous install and removes system directories and keeps settings.

Currently because of the themes cleanup, new icons and filename changes, many files that have been deprecated and or changed internal names stayed behind littering the global install directories.

This is particularly important to remove v1.0.0 of internal themes which are now obsolete and fallback by loading the v2 of theme on startup if needed.

Manually solving this is simple enough, but personally would rather users to have best experience possible with Interface visuals and dont have to dig into system directories needlessly and risk breaking something.

**Comment by DarthGandalf** [comment]
> personally would rather users to have best experience possible

Users on Linux use their distro's tools to install software for them (e.g. `emerge`), they don't always build programs from source manually. Package managers take care of removing files from old packages during upgrade.

> its a must for any app that you can compile

This is true, but it doesn't matter too much, because package managers take care of this regardless of what build system was used.

Here's what CMake says about this: https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F

> You cant uninstall a compiled KVIrc instance in Linux without this.

You can. But it requires some preparation. There are a few ways:
- Install to a dedicated directory, e.g. `/opt/kvirc` or `/home/user/apps/kvirc`, then to uninstall it, just `rm` that directory.
- Build a package (e.g. `.deb`) from the source instead of installing it directly, then to uninstall it, use the package manager, e.g. `apt-get remove`. When I was using Debian, `checkinstall` has been of great help for building such packages from source. It can create `.rpm` too.

**Comment by un1versal** [comment]
Thx for that cmake link, I think that would be the ideal and if done correctly shouldn't be so much of a risk as youde limit it to only to kvirc program files... No?
Having to jump trough hoops and use checkinstall do this do that, is not my idea of simple even if I personally can resolve the issue Im thinking of lesser able users and minimize support burden or having to write yet more documentation, I think we have way too much already.

 Im a fan of Kieeping it simple and stupid so, perhaps the cmake route would be my first shot.

**Comment by DarthGandalf** [comment]
"lesser able users" should install software using package manager of their distro, and not to manually compile it from source.

**Comment by un1versal** [comment]
I would agree normally, in an ideal world that would be true, but you know as well as I do and even better maybe that A) its not idea world, B) Nightly KVIrc packages dont exist for all distros prepackaged. C) Stable 4.2.0 doesnt count as its ancient and buggy.

Compiling is the only option in current cases until we have enough distros packagers to distribute prepackaged KVIrc.

**Comment by DarthGandalf** [comment]
How is it related to nightly?
It's job of package maintainers of a distro to keep the package up to date. KVIrc just needs to release a new version soon.

**Comment by un1versal** [comment]
> How is it related to nightly?
> It's job of package maintainers of a distro to keep the package up to date. KVIrc just needs to release a new version soon.

Seriously? You're hilarious

**Comment by DarthGandalf** [comment]
@un1versal if you don't want to believe me, it's not my problem.

`make uninstall` would make almost no difference. That's it.

**Comment by un1versal** [comment]
I dont disagree mind, but your talking about should's and maybes, thats not how the real world works, 

At the rate this is going it will be another 6 months to a year before KVIrc 5.x is ready.

And then what another 4 years for  the next release?

So, we need to live in real world... Not in this ideal world that doesnt exist.

Ideally speaking if we had nightly builds for OS X and a couple more main Linux distros with nightlies, this would be a non issue.

**Comment by un1versal** [comment]
make note.... this todo list were I based this request in was added in https://github.com/kvirc/KVIrc/commit/e5ff4ebd88df4df2e9504e678dbe1ba9cc8add6f

thats 2008, 4 years later 4.2.0 was released, it is now 2015 going on 2016, everyone is using broken ass KVIrc builds,

What we need is more distro and OSX packagers doing nightlies.

**Comment by DarthGandalf** [comment]
`cmake uninstall` won't help releasing next version sooner. Let's focus on fixing remaining issues for the next version _right now_.

Nightlies are fine, but proper release is much better.

**Comment by ctrlaltca** [comment]
Just to clear up some points:
1. first, this is a linux-only (osx) problem, only when KVIrc is compiled from source and installed globally using `make install`
2. As far as i remember and can see from the code, the `make uninstall` existed, but has been removed in 35699b83e9958c0e0eadc1b9beaaa6cb5ef6d190 . We could add it again just copypasting the code from https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F , but it will delete only files, not directories.

**Comment by un1versal** [comment]
I cant do more any faster.... and I barely scratched the surface.

**Comment by ghost** [comment]
There exist tools like `checkinstall` that a user can use if they want an automated uninstall. Personally, I feel they're the better option to relying on `make uninstall` (for users hand installing to /usr instead of getting a package from the distro's repo).

I'd expect most users hand-installing to install to /opt or ~/, but what do I know.

Maybe add an optional step in the install guide for something like this?

**Comment by un1versal** [comment]
Im personally avoiding like the plague documenting anything else like this, the docs are mammoth sized and mostly people don't read them —and even if they do, I already wasted many hours fixing docs and there's hundreds more hours required for website/wiki and documentation reorganization...

I rather the option that cause less support burden and less work for me as I have enough already.

So I imagine nothing will come of this and personally Im OK as is.

**Comment by un1versal** [comment]
closing since its useless feature request apprently
