### ISSUE TITLE
Optional "Set transparent or no background" when "Smart" Color nicknames is enabled

### ISSUE THREAD

**Issue by Zybyr** [kvirc/KVIrc#1563]
Hi Guys,

The background colors behind nicknames should be an option when "Smart" color nicknames checkbox is enabled, In my opinion it does not look good at all, and also difficult to read. 

In addition, an option to have colored nicks in the list of users of the channel would be really nice to have. The nick colors in the list of channel users column, should match the color in the chat of the same user when users write to the channel. I think hexchat would be a an example of what I mean. 

![background](https://cloud.githubusercontent.com/assets/11053449/9778485/e3354962-573e-11e5-80c4-6034c4a83e8a.png)

**Comment by un1versal** [comment]
> The background colors behind nicknames should be an option when "Smart" color nicknames checkbox is enabled, In my opinion it does not look good at all, and also difficult to read.

+1 here. I disable this feature on my themes precisely for this reason no matter if you have light or dark bg themes the issue is same.

> In addition, an option to have colored nicks in the list of users of the channel would be really nice to have. The nick colors in the list of channel users column, should match the color in the chat of the same user when users write to the channel. I think hexchat would be a an example of what I mean. 

That is already possible you can assign different colors to each user groups but only one color per each group is supported, So chan admin have one color, channel owners another, normal users another etc etc. and this works great in channels where theres varied user groups not so much where only 1 user type.

If you mean smart colors in user lists as well, I suppose this could be nice but to be honest I dont like the smart colors much so I cant really say much here.

And now Im really off to bed.

**Comment by un1versal** [comment]
Duplicated of #353 (seems this is an old issue).

After reading that ticket I vote for closing that ticket and keeping this open, this one has a better proposed solution.

Guys?

**Comment by pragmaware** [comment]
Disabling the background introduces a problem: what if the nickname color has bad contrast to the current user's background?

**Comment by un1versal** [comment]
Same color on same color would be bad that's sure, Thinking aloud here, isn't that something which can be avoided? As is doesnt seem ideal.

**Comment by pragmaware** [comment]
Well.. I remember writing that code the way it is explicitly to avoid the background problem.
The colors are in a table and are choosen to have reasonably good contrast (between fg and bg).

There is no safe way to exclude a foreground color (or a set of colors) that is too similar to the window background. .. or at least I couldn't think of one.

**Comment by un1versal** [comment]
That screenshot doesnt make the issue justice, it gets quite unreadable and hurts brain :D

The only thing that came to me immediatly was to color the nick only and leave the background out optionally, if then theres an issue of nick color + user bg becoming unreadable it cant be worst than this.

But tbh here it is, I switch this feature off (because of this) so to me this is a non issue since I dont really suffer it, though my vocalization is just emphatic to the people who do suffer it.

**Comment by un1versal** [comment]
merging with #353 and closing this
