### ISSUE TITLE
Revert introduction of capitalization errors for 'english'

### ISSUE THREAD

**Issue by Golutazem** [kvirc/KVIrc#1622]
A commit changed the capitalization of the word 'english' to be incorrect.
It is only correct to capitalize it when it is a proper noun or at the beginning of the sentence.

In the following example, it is a proper noun,
"The English fought William the Bastard and lost."

In the following example, it is not a proper noun and should not be capitalized,
"Many languages influenced the english language."

The commit introducing the errors is 624305ac108ee6efd9093ef0fb3c73f241982483.

However it also fixed an 'i' to I, which would be a fix desirable to maintain.

**Comment by un1versal** [comment]
@edakiri 

English as in the language is correct capitalized, it is a proper noun and its the English language referred to in most places. See for instance http://www.grammarly.com/handbook/mechanics/capitalization/10/capitalization-the-names-of-countries-nationalitie/

> In the following example, it is not a proper noun and should not be capitalized,
> "Many languages influenced the english language."

Sorry that is an incorrect example, based this comment for instance on https://en.wikipedia.org/wiki/Foreign_language_influences_in_English and here is my official -1 :-1: to this report.

The entries English -> english not capitalized in core are passable (since its not visible to public and we (pragma and I) discussed it and decided best not to risk breaking logic) but where it is documentation and public facing texts, Shouldnt we endeavor and avoid grammar bastardization and such things like the plague?

A good example of where the word English is not capitalized and acceptable. (not a proper noun) However it is capitalized in UK.

> 1959 Sunday Times 5 Apr. 4/5 The billiard term ‘putting on the english’, which Atticus states is current parlance in American bowling circles. The story goes that an enterprising gentleman from these shores travelled to the United States during the latter part of the last century and impressed the Americans with a demonstration of the effect of ‘side’ on pool or billiard balls. His name was English.

Extract from http://english.stackexchange.com/questions/38397/why-is-putting-some-spin-on-a-ball-described-in-some-circles-as-giving-it-some

**Comment by Golutazem** [comment]
I had looked into this before creating the 'issue'. Looking into it more, it appears that to capitalize English is and has been more popular. I retract my claim.

**Comment by swarfega** [comment]
Just to correct you, bastard is a description and not a name so doesn't need capitalising. Side note, in UK we don't use *ize so frequently and many words have changed to *ise.

**Comment by un1versal** [comment]
> Just to correct you, bastard is a description and not a name so doesn't need capitalising. Side note, in UK we don't use *ize so frequently and many words have changed to *ise.

What?

**Comment by Golutazem** [comment]
William the Bastard is more often written with a capital B, which indicates it is regarded as part of a title. Here you can see a comparison of frequency.

https://books.google.com/ngrams/graph?content=William+the+Bastard%2C+William+the+bastard&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2CWilliam%20the%20Bastard%3B%2Cc0%3B.t1%3B%2CWilliam%20the%20bastard%3B%2Cc0

I prefer Oxford English Dictionary (OED) to Cambridge. OED retains -ize for words which used it. Wikipedia also has an entry on Oxford_spelling, if interested.

**Comment by un1versal** [comment]
You guys are both bonkers **M**ad with a capital M
