### ISSUE TITLE
MDI child windows have an empty control menu

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1630]
![2015-09-18_10-29-56](https://cloud.githubusercontent.com/assets/75278/10122432/375db3f6-651a-11e5-860b-df6b68e4c8a7.png)

So this icon next to the word `KVIrc`, what does it do? It has no proper tooltip and when I click it, it leaves random channels. Maybe the channel I was last active in? The one that had focus at the moment I clicked? I don't know. I don't see the use in it and would like to hide it.

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Windows Release : 6.2.9200
System Version: Windows 8 Professional (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 58 Stepping 9

Build Info:
Build Date: 2015-09-19 22:32:46 UTC
Sources Date: 20150919
Revision Number: git-5394-g6375a3c
System Name: Windows-6.2
CPU Name: AMD64
Build Command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler Name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
```

**Comment by swarfega** [comment]
It changes according to what you have selected in the tree view on the left. So if you click on the server name it will change to the server icon. Actually just noticed a bug, it should be the same as the one in tree view but its some command prompt icon instead.

**Comment by wodim** [comment]
Such icon is standard in all MDI applications (granted, MDI applications are no longer common)

**Comment by wodim** [comment]
Clicking it once should open the control menu, which is empty (that's a bug). Double clicking it closes the MDI child window as it should. So I'll change the issue title.

**Comment by Stanzilla** [comment]
Can I still get an option to hide it though? :p

**Comment by wodim** [comment]
I am personally against adding options for everything, so that will be left up to whoever fixes it.

**Comment by Stanzilla** [comment]
Since you said MDI applications are no longer common and I haven't seen an icon in this place in a loooong time, I'm probably just for removing it altogether. The fact that it has been broken for so long and nobody complained about it, is a good indicator that nobody used it anyway.

**Comment by wodim** [comment]
I don't have an indication of it being broken for a long time. It could have broken when we transitioned to Qt5, for example.

**Comment by Stanzilla** [comment]
Eh, I thought the nightly builds are back on Qt4?

**Comment by wodim** [comment]
It worked before, but it used a hack, it seems. The empty control menu still appears, and a faux control menu is drawn over it. Unfortunately, that meant that the faux control menu does not automatically get focus and you must click it before you can use it. (Stating this just so it does not happen again when it's fixed.)

![2015-09-27_14-21-24](https://cloud.githubusercontent.com/assets/1001553/10122782/0579d3b0-6524-11e5-99e7-b1b587dc6a06.png)

**Comment by un1versal** [comment]
> Eh, I thought the nightly builds are back on Qt4?

Where did you get that idea from? Build logs from appveyor all point to Qt5.
Also Qt5 is preferred over Qt4 if both are present in system.

For whats its worth I think this icon should be gone when windows are maximized given that is useless and broken.

Makes sense when in this view
![1](https://cloud.githubusercontent.com/assets/3521959/10122969/8586db68-6522-11e5-83ed-517d637ecc29.PNG)

But no sense here
![2](https://cloud.githubusercontent.com/assets/3521959/10122950/08146f4c-6522-11e5-8fab-42dd81083a22.PNG)

**Comment by wodim** [comment]
Unable to reproduce on Ubuntu 15.04.

**Comment by wodim** [comment]
https://github.com/kvirc/KVIrc/commit/6374d76a93fc986b2d085f2d3baec0e55f0989dc

This restores the appropriate menu. I don't know if it's the solution we were looking for, though.

![2015-09-27_16-44-26](https://cloud.githubusercontent.com/assets/1001553/10123315/13b1a33c-6537-11e5-985c-9d972dab7f8b.png)

**Comment by Stanzilla** [comment]
The one on your last screenshot is a different one though? On Windows you have the KVIrc icon in the top left corner of the window, clicking it gives that frame, see 
![2015-09-27_19-07-30](https://cloud.githubusercontent.com/assets/75278/10124076/29798e82-654b-11e5-97f4-8b85dad6035c.png)

So you would end up with 2 icons doing similar things on the same side. The MDI handling button should maybe moved to the other, child-window related close/minimize etc buttons to the right?

**Comment by swarfega** [comment]
Yes, why doesn't move and size have icons?

**Comment by Stanzilla** [comment]
Maybe the original intention was proving a similar menu to the Windows default one on every other OS than Windows and it should just be hidden on Windows?

**Comment by Stanzilla** [comment]
@swarfega It never has icons, that's a default Windows menu.

**Comment by wodim** [comment]
1. MDI applications are applications that were very common a lot of years ago. MDI means _multiple document interface_ and it can be summarised in "windows inside a window". Nobody uses them anymore because they were awful. 
   
   ![](https://i.imgur.com/tFN42IB.gif)
   
   Obviously, we do.
2. The menu that was being shown before this modification is the one that is shown when you right click the window on the window list, thanks to a hack. That was not the right menu.
3. The new menu is the control menu. That menu is shown when you click the application icon on the title bar once, or when you right click on any part of the title bar. It is common in all window managers, not only Windows, and they contain the same set of basic window management actions.
   
   ![2015-09-27_20-18-02](https://cloud.githubusercontent.com/assets/1001553/10124425/0013f6fe-6555-11e5-8618-e25985bbc87f.png)
4. MDI child windows (i.e., the windows that are trapped inside a MDI application) also have such a menu. There's a catch, though: since those MDI child windows are inside the parent window, frameworks like Qt have to pretend those MDI children are controlled by the window manager, which they are not. That's the reason MDI children look so bad.
   
   ![2015-09-27_20-24-30](https://cloud.githubusercontent.com/assets/1001553/10124455/c5260fcc-6555-11e5-882d-189edbbf565e.png)
   
   And that's also the reason the control menu for those windows is Windows-like: they have to make up a menu, and they decided to mimic the Windows one.
   
   ![2015-09-27_20-24-55](https://cloud.githubusercontent.com/assets/1001553/10124460/e7b39d70-6555-11e5-9362-e88b920abda8.png)
   
   On Windows it definitely looks better, but not perfect.
   
   ![2015-09-27_20-28-50](https://cloud.githubusercontent.com/assets/1001553/10124487/706814de-6556-11e5-8b79-11cfa07ad49c.png)
   
   ![2015-09-27_20-28-58](https://cloud.githubusercontent.com/assets/1001553/10124489/74ae5580-6556-11e5-9bbb-aa9246fb1884.png)
   
   mIRC is also a MDI application and its MDI children look like have been taken straight off Vista.
   
   ![2015-09-27_20-29-42](https://cloud.githubusercontent.com/assets/1001553/10124498/8d43ee3e-6556-11e5-88f2-355636ddbed0.png)

Does it make sense to be a MDI application still? Anybody still tiling their MDI children? 

![2015-09-27_20-32-27](https://cloud.githubusercontent.com/assets/1001553/10124520/1be93d38-6557-11e5-84eb-700aee1c8bd6.png)

**Comment by pragmaware** [comment]
I also think that MDI doesn't really make sense anymore.
Removing it would simplify the code and probably eliminate a number of focus-related bugs.
Also in Qt5/KDE QMdiArea rendering is broken to the point it is hardly usable sometimes....

**Comment by Stanzilla** [comment]
@uNiversaI I had this on my mind https://github.com/kvirc/KVIrc/commit/face201e6e29935b177eb495ba03e3f73ad428da didn't see it was reverted though..

**Comment by wodim** [comment]
@Stanzilla it was undone after the relevant KVS classes were ported to Qt 5.

**Comment by Stanzilla** [comment]
Makes sense :)
