### ISSUE TITLE
Can't save themes

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1643]
It always fails with the message that it can't save an image to the theme. Unchecking `save icons`is a workaround.

![save_current_theme_-_kvirc_2015-09-30_22-06-20](https://cloud.githubusercontent.com/assets/75278/10205098/90b99dfa-67bf-11e5-88b5-648090ff8a0b.png)

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Windows Release : 6.2.9200
System Version: Windows 8 Professional (x64) (Build 9200)
Architecture: Intel64 Family 6 Model 58 Stepping 9

Build Info:
Build Date: 2015-09-30 01:21:42 UTC
Sources Date: 20150926
Revision Number: git-5439-g8ca6791
System Name: Windows-6.2
CPU Name: AMD64
Build Command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler Name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
```

**Comment by un1versal** [comment]
~~If they got corrupted you wont be able to.~~

~~You just reported https://github.com/kvirc/KVIrc/issues/1645 a triplicate report, now it makes sense to me, that if the icons are corrupted because of that bug, they cannot be saved into a theme, no?~~

In any case I dont recommend anyone be saving any icons into themes at this stage, this is why I requested this feature to optionally save icons to be added.
The rationale is, If I update any icons , change their names in core or add more specific icons the theme is already outdated and possibly broken.

**Comment by un1versal** [comment]
Well I just tested this and it does pop up this error on current master f5dc3c4baf6a30b2cbcc9a50c129a8564b22fa13 which confirms this report.

---

Maintaining the advisory notice on saving icons into themes. its not really a good idea tbh, since any themes that contain any icons overwrite the default ones and ignores any updates to core icons name or image updates like splashes and other non icons images.

Where people want to package different icons with their themes, they only need to include the icons they wish to replace and if they wish to replace all then this makes even less sense, but none-the-less it is helpful to the process as you need to know what you are replacing.

---

IMO this option should be off by default and carry some informational text. **EDIT** see #1647

None the less, this option should work even if people dont understand or care about outdated or dead icons or for some reason want to keep a specific version of all images with their themes.

**Comment by un1versal** [comment]
For reference sake this option was added in https://github.com/kvirc/KVIrc/commit/47c689858406fbaff052785be14a1e6e23b6787c

**Comment by un1versal** [comment]
this is broken still... or came back again for some reason.

**Comment by un1versal** [comment]
was fixed again in https://github.com/kvirc/KVIrc/commit/bcb3f9180629e0ead81042bfe9c3323701b7b679
