### ISSUE TITLE
List of fixes and improvements necessary for OS X

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1704]
I'm making a list of oddities the OS X version has. It has always been a second class citizen and it is time to change that...
- [x] "Aria" and "MinimalDark" have hardcoded "DejaVu Sans Mono" as the default font.
- [ ] Default font for some things is Lucida Grande, we mustn't hardcode that.
- [x] In settings dialogs, the first section opens automatically (for example, _Input_ in _Theme Settings_) after the opening animation finishes for whatever reason.
- [x] In settings dialogs, there is not enough margin between some options (checkboxes notably).
- [ ] Some labels lack padding.
- [ ] The menu extras/indicator icon needs to be done, by now we have a greyed out version of our main icon.
- [x] Menu entries should not have icons. -- #1708
- [x] Menu labels look bad, and the menu label that there is in the menu extra icon does not appear at all.

According to some guy on IRC, this is a bug on Qt related to DPI that will be fixed with the future release of Qt 5.6 (`setAttribute(Qt::AA_Use96Dpi, true);`):
- [ ] Fonts don't have the same size on OS X, a _10_ font on OS X has a size similar to that of an _8_ font on Linux or Windows. Maybe the difference is whether the units are taken as pt/px? (Edit: problem is most probably that Windows and Linux use 96 dpi by default while OS X uses 72 dpi).
- [ ] Font for the multiline editor is also too small by default.

**edit**
- [ ] shortcuts for OS specific... (refactor shortcuts suchs as ctrl+something in all string instances to be OS aware.) see https://github.com/kvirc/KVIrc/issues/1345

**Comment by un1versal** [comment]
I agree with the fonts comment, but, here is the snag, fonts shipped with one OS or assigned by a theme dont necessarily work for all OS or even exist there. Hence I created https://github.com/kvirc/KVIrc/issues/1574
I agree that the basic look of KVIrc should be homogeneous across all OS

> "Aria" and "MinimalDark" have hardcoded "DejaVu Sans Mono" as the default font.

So what do you suggest? something has to be hardcoded you cant not have no font. and again the comment above applies here.

> In settings dialogs, there is not enough margin between some options (checkboxes notably).

Yea Qt is about as consistent across OS as a fart in the wind.

> Some labels lack padding.
> 
> Menu labels look bad, and the menu label that there is in the menu extra icon does not appear at all.

Same comment as above, in fact take that comment and apply it to most of your list.

Font sizes Im in favor of bigger rather than smaller but not everyone has super high def screens.

> Menu entries should not have icons.

Absolutely NOT, no way jose. Ive put tons of hard work and many many hours into this. so naturally Im against this 100% + 1000%

Why does ANY application have to be designed to fit any fartsy OS no matter what OS that is?

**Comment by DarthGandalf** [comment]
> I agree that the basic look of KVIrc should be homogeneous across all OS

No. All applications on the same OS should have homogeneous look.
I don't want some application on Linux to look like it's Windows.

**Comment by un1versal** [comment]
> No. All applications on the same OS should have homogeneous look.
> I don't want some application on Linux to look like it's Windows.

Well good luck with that endeavour. so we have Linux, Debian, Arch, etc etc and many desktops flavours all look different, + Windows xp, vista, 7, 8, 10 + OSX so when you completed the 500000 (a guesstimate) icons necessary to fill that ideology, let me know.

**Comment by DarthGandalf** [comment]
I'm not speaking about icons, but about the look in general.

**Comment by wodim** [comment]
> So what do you suggest? something has to be hardcoded you cant not have no font. and again the comment above applies here.

I suggest that we should allow some magic word to be used (like "monospace") that KVIrc converts into whatever is appropriate for the target OS.

> Absolutely NOT, no way jose. Ive put tons of hard work and many many hours into this. so naturally Im against this 100% + 1000%

Bad luck, because all apps on OS X sport no menu icons.

**Comment by un1versal** [comment]
> I'm not speaking about icons, but about the look in general.

For me a look is the complete lot, something that fits all platforms all OS must have a full matching look. Icons are the obvious flaw in this ideology and the most obvious.

> I suggest that we should allow some magic word to be used (like "monospace") that KVIrc converts into whatever is appropriate for the target OS.

Ive discussed this with pragma, he was going to look into it.... Im open to ideas that work.

> Bad luck, because all apps on OS X sport no menu icons.

Ive put a lot of work into the icons designing them to fit the specific actions and assigning the right icons in menus. So if you start throwing my work out the window...

**Comment by wodim** [comment]
It goes without saying that nobody is throwing nobody's work out the window, the change I am proposing is to remove icons in menu entries on OS X in the best interest of consistency with the rest of the system, that's all.

**Comment by un1versal** [comment]
So what you are proposing is, that you will only do this for OSX, and that other oS wont be affected by this change right?

So then explain the reasoning, why do you think its a good idea to make an application look different per OS.

**Comment by wodim** [comment]
Actually, as per discussion on IRC, we have decided to remove all icons from all platforms, and not only from menus but from almost everywhere else, including settings dialogs, the ircview, the user list and several other places. I am preparing a pull request for such change.

**Comment by DarthGandalf** [comment]
Who are "we"? Discussion with whom? How would empty buttons look like?

**Comment by un1versal** [comment]
Assuming you are serious, the only way I would ever support such drastic move is to make that optional and the default being what is now.

user modes and such would never work and would break function design.

But I presume you talking out of your ass like usual and "we" means you, yourself, and only you.

**Comment by Heufneutje** [comment]
I find this a bad idea. ESPECIALLY in the settings dialogs. Since KVIrc is so highly configurable the settings dialogs are pretty big and the icons add a lot of clarity.

**Comment by pragmaware** [comment]
I suggest adding an option to avoid showing icons, off by default, so the client will look the same on all the platforms initially. If someone wants to have a mac-ish look without icons he will activate the option.
It shouldn't be very hard to do. See
   http://doc.qt.io/qt-4.8/qaction.html#iconVisibleInMenu-prop
and
  Qt::AA_DontShowIconsInMenus attribute for QApplication.

**Comment by ctrlaltca** [comment]
We already have such an option (boolShowIconsInPopupMenus), but it didn't update the existing actions, so it required a restart to work. Addressed in #1708

**Comment by wodim** [comment]
9 checkboxes, all comments are about something that deserves no discussion, because that's the way OS X does it.

:information_desk_person:

**Comment by un1versal** [comment]
Number 11 

> Icons in the theme manager are huge. Maybe my fault. :<

Thats down to https://github.com/kvirc/KVIrc/commit/31135fb0bbcd9a12b5a19990c28e5ccdcf4b06f6

Imo this is a huge mess.

The problem that (NOT) being solved there is that the screenshots were shown at 32x32 and you cant tell how a theme looks form that size, however not all themes have screenshots, hence I added a CHEAT ICON to the internal ones and because of that limitation.

The thing is after https://github.com/kvirc/KVIrc/commit/31135fb0bbcd9a12b5a19990c28e5ccdcf4b06f6 the screenshots are still too small and now those icons are huge.

I would rather it was back to what it was before https://github.com/kvirc/KVIrc/commit/31135fb0bbcd9a12b5a19990c28e5ccdcf4b06f6, and add some live preview on mouseover that shows a largest screenshot available if any on theme. and allow the icons to say at normal size.

**Comment by wodim** [comment]
@un1versal I doubt it’s supposed to look like this.

![screen shot 2015-11-10 at 11 50 32](https://cloud.githubusercontent.com/assets/1001553/11060557/47bb5d76-87a1-11e5-906e-2f174955869e.png)

**Comment by un1versal** [comment]
Again, read what I said.

**Comment by wodim** [comment]
Oh, I guess they are supposed to be screenshots then.

**Comment by un1versal** [comment]
yes, but even if they were they are still too small and that https://github.com/kvirc/KVIrc/commit/31135fb0bbcd9a12b5a19990c28e5ccdcf4b06f6 solved nothing, just made this worst.

**Comment by wodim** [comment]
That size is good enough for a small screenshot anyway, at least to see the colours and stuff.

**Comment by un1versal** [comment]
I disagree strongly with that assessment, not everyone can tell what they need to know from the small screenshot even at this bigger size (its better than 32x32 but that imo is just as bad). As is is **far** from ideal..

If I was that proficient at coding, I would do that one of two ways for handling this for everyone in no half measures.

Solution 1) Revert https://github.com/kvirc/KVIrc/commit/31135fb0bbcd9a12b5a19990c28e5ccdcf4b06f6 and make a live preview on mouse-over or something.
Because not all themes have screenshots and no one is updating them all. (Im not touching that with a 10ft pole)

2) Change the layout of this dialog; so the screenshot takes the whole horizontal row adn the descrition is below the screenshot.

Ill make some mocks

**Comment by wodim** [comment]
2 would look awful, I do not know if you have imagined how it would look like, you really should.

1 is a very good idea, you could take the screenshots yourself for the default themes.

**Comment by un1versal** [comment]
This is a very loose idea, but it servers to illustrate what could be like, and imo it can be done better, I just dont wanna spend more time on these mocks.

Solution 1 mock
![solution 1](https://cloud.githubusercontent.com/assets/3521959/11061859/ee386c0c-87a1-11e5-85ff-d554d4c6f961.png)

Solution 2 mock
![solution 2](https://cloud.githubusercontent.com/assets/3521959/11061868/ff678314-87a1-11e5-857f-f02c90a0b657.png)

**Comment by un1versal** [comment]
nr 11 is not a OS X specific issue (so consider removing form this list) See https://github.com/kvirc/KVIrc/issues/1737 as above discussion should take care of that.

**Comment by un1versal** [comment]
Added https://github.com/kvirc/KVIrc/issues/1345 to first post.

**Comment by wodim** [comment]
kek, Qt 5.6 was postponed until February the 9th (by now) https://wiki.qt.io/Qt-5.6-release

**Comment by un1versal** [comment]
> The menu extras/indicator icon needs to be done, by now we have a greyed out version of our main icon.

whats this? screenshot or something

**Comment by wodim** [comment]
We are talking about these icons (the ones with "mono" in the name): https://github.com/kvirc/KVIrc/tree/master/src/modules/trayicon

They should look roughly like these ones:

![yosemite-default png_ 2880x1800 _-_google_chrome_2016-01-13_12-39-04](https://cloud.githubusercontent.com/assets/1001553/12293264/aaefb742-b9f2-11e5-9471-db3247d27565.png)

i.e. completely black.

**Comment by un1versal** [comment]
I hate our tray icons :grinning: , trying to put too much into a small area makes it look like brain farts way too crowded and no one can actually see wtf is going on...

ill see what I can do to all (most) of them

**Comment by un1versal** [comment]
one small contrib part of last entry https://github.com/kvirc/KVIrc/pull/2009/commits/d7fb738d459456cef1fe2b793fd874ff6763712a

**Comment by un1versal** [comment]
> "Aria" and "MinimalDark" have hardcoded "DejaVu Sans Mono" as the default font.

Not anymore after https://github.com/kvirc/KVIrc/commit/47d383d7d7f2e86037aff64b499f4441beba2f60

thats pretty much the fonts from v.1.0.0, these however break the UI as it introduces scroll bars by tabs in some places.

![capture](https://cloud.githubusercontent.com/assets/3521959/16711876/5b9fe88e-4669-11e6-99b5-f042693702e0.PNG)

love it.

**Comment by wodim** [comment]
Closing and writing another issue.
