### ISSUE TITLE
Save console log files with an actual context name

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#1710]
Because
![](http://i.imgur.com/5TUhkDF.png)

doesn't really mean much to me as I load my networks in a different order each time, making finding things within logs nearly impossible.

**Comment by ghost** [comment]
What kind of a name would you want them to have? Since you can use the same console for multiple IRC servers without closing the console (I.E. you could connect to freenode, disconnect, then connect to rizon, and they'd all log to the same console), I can't really think of what name could be given to it to make it meaningful.

**Comment by un1versal** [comment]
With https://github.com/kvirc/KVIrc/pull/2050 compiled in... no change but... Well I added a space a while back between console and ID...

![capture](https://cloud.githubusercontent.com/assets/3521959/16705784/de2d4dce-458c-11e6-9f6b-09325d979a11.PNG)

However looking at the code and the text here against what other windows do like channels it seems to me `console_#_date` **on** is supposed to have something after the **on**

channels for instance have the server/network name

To be perfectly honest what @TheReign had said wouldn't be a problem because if a connection is dropped and context reused then logging should account for disconnect and network value being different and open new log with that new server/network under same ID then...

easier said than done I know.
