### ISSUE TITLE
running options.dialog <something> opens a Preferences dialog with no settings. 

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1754]
The docs say 

```
Shows the KVIrc options dialog for the specified options group. If the [-t] switch is used, the dialog is opened as toplevel window, otherwise it is opened as part of the current frame window.
Valid values for [options_group] are "general" and "theme". If [options_group] is omitted, the option group "general" is assumed. This command is exported by the "options" module.
```

But if you run  `options.dialog <something>` where `<something>` is not **general** or **theme**,  the unexpected happens.

![capture](https://cloud.githubusercontent.com/assets/3521959/11628177/d21b84a4-9ce7-11e5-978f-f1a020e92dc5.PNG)

*_also_ `options.dialog -t general` does the same and omitting `-t`

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.13.0-68-generic
System Version: #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015
Architecture: x86_64
Qt Version: 5.2.1

Build Info:
Build Date: 2015-12-05 13:58:43 UTC
Sources Date: 20151205
Revision Number: git-5745-gd82a8a8
System Name: Linux-3.13.0-68-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: N/A
Qt Version: 5.2.1
```

**Comment by un1versal** [comment]
I also dont think `$options.isdialog` is working properly either, it returns 0 always. but thats another bug there I think.

**Comment by ghost** [comment]
I question whether this is really a bug or not.  What should happen when a user uses `options.dialog <something>`?  The only way I see to restrict this would be to add a check to see if the parameter passed is "general" or "theme" and either force it to "general" (which is what empty parameter does) or just not do anything/return an error.  Forcing it to "general" would require the same method to be added to `$options.isdialog` and `options.close` to keep it consistent and so a script won't break if you open it with `<something>` but can't close it with `<something>`.

Now, what happens if in the future we were to make DCC it's own [options_group]?  Now we've got to remember to add this new [options_group] to the valid list.  Theoretically this leaves it open for additional [options_group]s to be added, but I guess that's not very likely.

For reference, the code in question is in:
File: `src/modules/options/libkvioptions.cpp`
Function: `static bool options_kvs_cmd_dialog(KviKvsModuleCommandCall * c)`

Also, I tested `$options.isdialog` and it works properly for me.  Remember that it only returns 1 while the dialog is open.  It even returns 1 if I do `echo $options.isdialog("asdf")` after doing `options.dialog asdf`.

**Comment by un1versal** [comment]
This opens either general preferences dialog or the themes preferences dialog only, I dont think this command was made to open specific settings group, so seems to me this should have better checks to prevent blank dialogs from popping up it seems.

To open specific set of options you use `options.edit <options_page_class_name:string>` which DCC is `OptionsWidget_dcc` or no?

**Comment by wodim** [comment]
As @TheReign said I took a look at the code and it looks like it's done on purpose, although I don't understand what the reason is.

**Comment by un1versal** [comment]
Well it looks broken design to me. It makes no sense to do this as it serves no purpose... Low priority as it may be.

**Comment by ghost** [comment]
So what should it do?  Default to "general" or return an error?

**Comment by un1versal** [comment]
IMO the best handle is to default to general like you have if you enter none or some argument other than general or theme is passed perhpas with some message about it on console specifying valid arguments.

But Im easy here, anything other that what happens now is an improvement.
