### ISSUE TITLE
Opening Mode Editor when server is disconnected = KVIrc crash

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1766]
How to make kvirc crash in 5 easy steps 

1) connect to any server 
2) Join any channel 
3) Disconnect from server but leave channel up 
4) Select the channel 
5) Now open Mode Editor

 Crash

Havent tested in windows.

```
KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.13.0-68-generic
System Version: #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015
Architecture: x86_64
Qt Version: 5.2.1

Build Info:
Build Date: 2015-12-12 15:39:58 UTC
Sources Date: 20151212
Revision Number: git-5814-g4c13a76-dirty
System Name: Linux-3.13.0-68-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: N/A
Qt Version: 5.2.1
```

**Comment by un1versal** [comment]
Apparently any ban/invite/topic editors (they not called that but you know which they are) also crashes.

**Comment by ghost** [comment]
Bug is in `void KviMaskEditor::updateOpStatus()` where `m_pChannel->connection()->userInfo()` returns an invalid pointer due to the server being disconnected.  Probably either need to check for valid pointer or just check `m_pChannel->connection()->state()` is `Connected`.

Edit: Can't check `m_pChannel->connection()->state()` without a connection... >.<  silly me

I don't see a reason for the mask editor to be enabled while server is disconnected.

**Comment by ghost** [comment]
Here's a partial fix for it: https://github.com/TheReign/KVIrc/commit/b90dac7f9b142e85f58927221999928b3f8127cf

The mask editor doesn't crash anymore, but the titles are `Mode "b" Masks` now. Not a big deal since it's unknown what it _should_ be with the server disconnected.

The mode editor still crashes.  I haven't found the other bug in it yet.

**Comment by staticfox** [comment]
I have a fix for the mode editor if you wanna PR yours for the masks
