### ISSUE TITLE
Edit fields that whcih contain plain text entries -> should be placeholder()

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1781]
Currently dialogs such as
Add Profile
![capture](https://cloud.githubusercontent.com/assets/3521959/11971183/df63bb4a-a930-11e5-9e51-ae2f05a643dd.PNG)

and other contain some [plaintext](https://github.com/un1versal/KVIrc/blob/d054e9a0d010138fbb9924dafdb7c6e7de29dd61/src/modules/options/OptionsWidget_identity.cpp#L712-L719) instead of placeholder text,

Thers many many dialogs that suffer from this and when a user tries to fill in those entries more often than not you end up with remnants from that text 

Some Qt savvy person would help on this would be fantastic and Ill collect all dialogs here that suffer from this.

**Comment by un1versal** [comment]
Server -> Enable NickServ Identification https://github.com/kvirc/KVIrc/blob/973649f82e5543a84f71b384a3f1bc9741007874/src/kvilib/irc/KviNickServRule.cpp#L38-L51
![capture](https://cloud.githubusercontent.com/assets/3521959/11971410/406ceffc-a935-11e5-8803-128a8bfc2d67.PNG)

and

![capture2](https://cloud.githubusercontent.com/assets/3521959/11972622/d0458ac4-a946-11e5-9dc9-f66f012bbd92.PNG)

Theres probably others I missed...

**Comment by ghost** [comment]
Simple change you can do yourself: http://doc.qt.io/qt-5/qtextedit.html#placeholderText-prop

Note: It says Qt 5.2, not sure if there's a way to have Qt4 do placeholder text.  Might be able to do preprocessor #if for Qt versions, but that's dirty, in my opinion.

Also, for the NickServ Ident  dialog, mask/regexp/command should not be placeholder text. Those are good defaults to have or else it'll confuse users if they're placeholder text rather than editable text.

Edit: I mixed up QTextEdit with QLineEdit >.< http://doc.qt.io/qt-5/qlineedit.html#placeholderText-prop

Available since Qt 4.7

**Comment by un1versal** [comment]
Yep... I cant manage the Qt4 bits, so not sure if I will try. but thanks Ill look into it for sure.

**Comment by ghost** [comment]
I like how the OK and Cancel button order is flipped on the foreground window and background window for the NickServ one.

**Comment by un1versal** [comment]
You noticed eh... theres more of those too :D

**Comment by wodim** [comment]
I dealt with them all, now I'm waiting for you to wake up and complain about how I did it :information_desk_person:
