### ISSUE TITLE
Add option to send WHO output to the console

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1815]
We have options such as "send WHOIS to the active window" that send the output to the console when they are disabled. We need to add the same for WHO options and disable it by default so replies go to the console.

Many people are having that problem of being connected to a bouncer from several places at once and therefore are being spammed all day with WHO replies. The solution is to load the `route_replies` module on znc but I bet a lot of users can't be arsed to investigate it and just ditch KVIrc altogether.

**Comment by un1versal** [comment]
+1 for routing any and all such noise to console

**Comment by ghost** [comment]
I propose having a `KviOption_boolWhoRepliesToConsole` instead.  That way, when it is set to false (which would be current functionality) when KVIrc does the auto-who on channels, they would remain being sent to the channel rather than the active window.

Although, I'm kind of in favor of adding a `chan->sentAutoWhoSync()` (for the auto away update) or using the `chan->sentSyncWhoRequest()` flag for it and just halting the output for those, which would negate my opinion above.
