### ISSUE TITLE
Shortcuts must be hit twice

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1831]
After 4cae25e most shortcuts must be hit twice for them to work.

**Comment by ghost** [comment]
I can't reproduce this on linux.  Probably need more information.

**Comment by staticfox** [comment]
Confirmed issue on my end using windows

**Comment by ghost** [comment]
Might be localized to Windows builds. I can't think of a reason that would be specific to Windows and not Linux.  Feel free to remove that commit, it's only an aesthetics fix to the menu so the shortcuts look proper.

**Comment by wodim** [comment]
I can reproduce it on Windows and Linux. I'll see if I can fix it.

**Comment by un1versal** [comment]
Have you compiled without that commit to confirm it was the culprit?

In any case I can **half** confirm this here Linux side with current build.

For instance `ctrl + w` works first time always. (exit channel) or `ctrl + tab` also `ctrl+Q` always works (probably others also work didnt test all),  but things that trigger windows or some 3 key combination, need double hit in a row.

If you hit one shortcut and then another and come back to hit same one again, this does nothing, seem it must be hit twice in row.

> Feel free to remove that commit, it's only an aesthetics fix to the menu so the shortcuts look proper.

I was never a fan of ripping something out rather than fixing it, esecially when you fix something with a particular commit.

**Comment by un1versal** [comment]
FYI here is a revert commit for https://github.com/kvirc/KVIrc/commit/4cae25e5ee6c63cec7248d97216de7f69c2bc5cd I created for testing ontop of master.

See https://github.com/kvirc/KVIrc/commit/de9c634e4b584dbda27cf3cb6e4a166851927c79

**Comment by ghost** [comment]
> I was never a fan of ripping something out rather than fixing it

@un1versal I'd "fix" it, but I can't reproduce the issue to be able to test a "fix".

**Comment by un1versal** [comment]
Not on your linux, have you tried a window build or maybe another distro? What is your distro anyway?
Is there a difference between starting kvirc via terminal vs not? What style are you using?

This is linux mint here

```
KVIrc 4.9.1 'Aria'

Runtime Info:
System name: Linux 3.13.0-71-generic
System version: #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015
Architecture: x86_64
Qt version: 5.2.1
Qt theme: fusion

Build Info:
Build date: 2016-01-08 21:39:56 UTC
Sources date: 20160102
Revision number: git-6093-ga6a3370
System name: Linux-3.13.0-71-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.2.1
```

Well it was 4cae25e that did it, compiling with revert https://github.com/kvirc/KVIrc/commit/de9c634e4b584dbda27cf3cb6e4a166851927c79 fixes the issue.

**Comment by wodim** [comment]
You could try with a fresh profile.

**Comment by wodim** [comment]
I have reverted it until it's sorted out.

**Comment by un1versal** [comment]
if you have reverted it this bug is gone
