### ISSUE TITLE
Input not taking theme settings correctly on Win8+

### ISSUE THREAD

**Issue by talentedmrripley** [kvirc/KVIrc#1853]
No matter what color I choose the Input area background remains white.  This happens on Windows 8.1 and 10.  Also the channel mode area, to the right of the topic, remains white as well after being changed.

**Comment by un1versal** [comment]
if its anything like https://github.com/kvirc/KVIrc/issues/1623 thats been fixed (twice) so you'll need to upgrade your current build. 

Since we dont know what version you are running, because you left out the most important part (wink), in future please read and follow https://github.com/kvirc/KVIrc/wiki/Submitting-a-bug-report#information-required-when-making-a-bug-report-via-github-issues

For upgrades follow https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrc's-nightly-source-or-binaries

**Comment by wodim** [comment]
Download a new version from http://kvirc.d00p.de/
