### ISSUE TITLE
Tabs in the IrcView not displayed properly

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1855]
![2016-01-27_15-34-21](https://cloud.githubusercontent.com/assets/1001553/12616455/8cb2a572-c50b-11e5-8284-5b2a641f2ce9.gif)

pls fix

**Comment by un1versal** [comment]
https://github.com/kvirc/KVIrc/wiki/Submitting-a-bug-report#information-required-when-making-a-bug-report-via-github-issues

lol

**Comment by un1versal** [comment]
Works fine here in trunk, if still and issue provide build information and reopen

**Comment by un1versal** [comment]
[14:59:59]  <wodim>     yes hello   there
[15:00:04]  <wodim> click that
[15:00:04]  <wodim> /say $char(9)yes$char(9)hello$char(9)there
[15:00:07]  <staticfox> ok yeah that is broke

**Comment by un1versal** [comment]
This issue is also visible present with some aliases Usage string

type 
1) `/usermodename`

2) then select the text below Usage:

![tabs](https://cloud.githubusercontent.com/assets/3521959/16673099/014cc27a-44a3-11e6-939a-a3525ae4e4bd.gif)

and clicking the test above

![tabs](https://cloud.githubusercontent.com/assets/3521959/16672770/338e70f6-44a0-11e6-8847-3c82cb62e49e.gif)

and this is bug #2051 (I know #1855 != #2051 its not same bug, but the way it presents itself is somewhat similar)
![unicode](https://cloud.githubusercontent.com/assets/3521959/16672865/d2485e14-44a0-11e6-91f2-ef2c3c163cc9.gif)

**Comment by sloanonlinux** [comment]
I has this bug too, version: 4.9.2

**Comment by wodim** [comment]
When we print text in the ircview, we make one call to QPainter.drawText for every line. If the text has tabs, the tabs are wrapped at regular intervals. You can check this writing an alias like this:

    echo $char(9)yes$char(9)hello$char(9)there
    echo $char(9)yes$char(9)hellofriend$char(9)there

![image](https://user-images.githubusercontent.com/1001553/29744330-426ab450-8aa3-11e7-8d0b-ccc6529dfc4d.png)

When you select text, on the other hand, three calls to drawText are made: one for the text before the selected block, another for the text in the selected block, and another for the text after the selected block. This means there are three different origin points for the text drawn with drawText (one for each chunk of the line), which in turn means the tabs wrap at three different places now.

Since such a bug is unlikely to ever be fixed by anybody, I propose we replace all tabs with one or eight spaces when painting them.
