### ISSUE TITLE
Make serverdb.kvc optional in the installer

### ISSUE THREAD

**Issue by Cpuroast** [kvirc/KVIrc#1901]
This is especially useful for people who use BNC instances like ZNC, where the direct connections to the various IRC networks are irrelevant.

It would be nice to make the included "serverdb.kvc" file optional in the installer, where one could simply un-check it.

I end up going in the program files folder and nuking it after every upgrade before re-starting KVIRC.

**Comment by un1versal** [comment]
> I end up going in the program files folder and nuking it after every upgrade before re-starting KVIRC.

Why dont you **delete the server entries via server and configuration dialog**? That would be **the correct** way btw **not nuking the fie directly**
Or if you prefer, open the serverdb.kvc i you favorite editor and delete the contents and save file...

Whats happening is **by physically deleting the file** instead of having an **empty file**, each time you upgrade **the file** is recreated with defaults.

If file exists even if empty nothing happens and you never have to do this again.. and you can even go a step further and make file read only.

If this resolves your issue let me know.

**Comment by ctrlaltca** [comment]
I think everyone is not interested in the whole list of server we bundle with kvirc, they just enable the few they use and ignore the rest. I could be nitpicking, but adding an option for everything is just bad design, and KVIrc is already full of options.

**Comment by DarthGandalf** [comment]
I use ZNC, and I just ignore the existing networks; they are irrelevant but they don't hurt either.
I added several more networks via the configuration dialog, with the only server pointing to my ZNC.

**Comment by un1versal** [comment]
A while back @staticfox mentioned he was working or had plans to implement a front end for bouncers or something of the sort, that probably better option rather then spend time (people clearly dont have) developing any solution like is suggested here.

I think my suggestion should work for @Cpuroast anyway and thats an edge case so suited for a simple workaround as suggested.
