### ISSUE TITLE
[Feature Request] [Windows] Option to hide the menu bar

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/KVIrc#1915]
New option under settings => toolbar to hide the menu bar and only show it when `ALT` is pressed.

**Comment by wodim** [comment]
New option under settings => toolbar to get loads of people in our channel asking where their menu bars went.

**Comment by Stanzilla** [comment]
Make it (the option) off by default, ofc!

**Comment by wodim** [comment]
I will implement it, probably. But people will disable the menu bar and then won't know how to make it return, that is a fact.

**Comment by un1versal** [comment]
In Linux this is easy, install appmenu-qt5 and watch KVIrcs menu disappear.

**Comment by un1versal** [comment]
Just so comments arent lost, the menubar should always be visible by default with possibility to hide/unhide by pressing Alt.

I also think just in case we should have some sort of visual indicator on statusbar whem menubar is hidden via this method..
This suggestion is because of what I written above, by installing appmenu-qt5 it breaks KVIrcs menubar (hides it permanently) and then we wouldnt know if its because of this or because of that when ppl complain. @1977David already complained to me about the menu being gone on his build.
Coincidentally I only found out about appmenu-qt5 tonight idk yet if thats the reason for his issue but it does cause it here when tested.

**Comment by un1versal** [comment]
> I also think just in case we should have some sort of visual indicator on statusbar whem menubar is hidden via this method..
> This suggestion is because of what I written above, by installing appmenu-qt5 it breaks KVIrcs menubar (hides it permanently) and then we wouldnt know if its because of this or because of that when ppl complain. @1977David already complained to me about the menu being gone on his build.
> Coincidentally I only found out about appmenu-qt5 tonight idk yet if thats the reason for his issue but it does cause it here when tested.

The suggestion above is due to https://github.com/kvirc/KVIrc/issues/1917 (4 user reports in total for that issue over IRC)

**Comment by 1977David** [comment]
Hello...

After removing appmenu-qt5 the menu did appear again. So all fine now. 

See here:

https://github.com/kvirc/KVIrc/issues/1917

**Comment by un1versal** [comment]
fixed by #1919
