### ISSUE TITLE
No menu at the top anymore

### ISSUE THREAD

**Issue by DaVukovic** [kvirc/KVIrc#1917]
### Expected behavior

The expected bahavior would be like this:

![kvirc1](https://cloud.githubusercontent.com/assets/7235787/14226093/7252b3e2-f8d8-11e5-85ec-a66d5bff7b67.png)
### Actual behavior

The actual one is like this:

![kvirc2](https://cloud.githubusercontent.com/assets/7235787/14226101/95114ef2-f8d8-11e5-9b20-d256b14f3ade.png)

And I don't know how to get it back. I just compiled the version from source and this is how it ends up.
### System information

about:

![aboutkvirc](https://cloud.githubusercontent.com/assets/7235787/14226128/4e0884ac-f8d9-11e5-9266-97120bc20120.png)

uname -a:

Linux david-kubuntu 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/lsb-release:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

Let me know if something is missing.

Cheers

**Comment by un1versal** [comment]
Thx David.

This is now a quite an old issue unreported in tracker till now.

A known cause for this issue (after many tests) is that `appmenu-qt5` when installed causes this... uninstalling it fixes it, however your issue doesn't seem related to that afaict.

I made a suggestion in https://github.com/kvirc/KVIrc/issues/1915#issuecomment-204617058 because of this issue because that will potentially add to confusion with users that have this problem here (I have 3 other reports over IRC for this)

**Comment by un1versal** [comment]
**Somemore information:** related to `appmenu-qt5`its a valid component for other applications but it affects some apps + KVIrc in this manner as well. (menu disappears) 
reference https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

As for the cause for this issue #1917 reported, the cause is **unknown** afaik at this time.

In case of `appmenu-qt5`as cause we can ask ppl to remove it if it doesn't affect

**Question:** Can we do something in kvirc to prevent appmenu-qt5 from causing this issue?

**Comment by un1versal** [comment]
@1977David you have KDE installed or something? Using Plasma5?

**Comment by DaVukovic** [comment]
@un1versal 

yes I use KDE with Plasma 5 (Kubuntu 14.04.4) 

After removing appmenu-qt5 the menu bar was back. 

see here:

![aboutkvirc1](https://cloud.githubusercontent.com/assets/7235787/14232210/9dc6131e-f9a2-11e5-912a-d650a808fec5.png)

Everything like expected

thx

**Comment by un1versal** [comment]
@wodim can we workaround this appmenu-qt5 issue?

I spoken to the other 2 remaining users in the last 10 minutes
3 users Including @1977David  have now confirmed that without appmenu-qt5 it restores menu. 1 person said he doesnt have that file, but is using some Debian self compiled real cutting edge stuff including alpha Qt 5.7. idk where to proceed there or if we should care at this stage for that cutting edge stuff.

**Comment by wodim** [comment]
@un1versal make it so they try it after 99925aa, because I downloaded Kubuntu 14.04 and I could not reproduce the issue.

**Comment by DaVukovic** [comment]
@wodim does that fix mean, you force to disable appmenu-qt5 even it's installed while running KVIrc?

If yes, I would compile, install appmenu-qt5 again and see, if that fixes it.

**Comment by wodim** [comment]
@1977David that's what it does, yes.

**Comment by un1versal** [comment]
yes please test and confirm it fixes it, Im sure it does in any case.

**Comment by un1versal** [comment]
This is a Qt 5.2.1 bug, since https://github.com/kvirc/KVIrc/commit/99925aa796ad1319f6f374fedc9a6d5907294b36 has been merged this is fixed + discussion there will mean this is will be fixed by external workarounds even if that fix is removed.
