### ISSUE TITLE
New server info status bar applet text is way too verbose

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#1988]
Before it was

> **[irc.server.com]** nick (+kek)

Now

> Using server: **irc.server.com** - Modes for you: **+kek**

The new text is way too verbose. It reads like a tooltip. I think it's inappropriate.

**Comment by staticfox** [comment]
The old way also included the user modes as well

**Comment by wodim** [comment]
Yeah my bad. Doesn't change the point of it though

**Comment by un1versal** [comment]
all that was added was labels, Using server: someserver and and Modes for: nick

which if theres no modes set it will only show nick which wasnt even possible before.

The labels tie to all other entries making it consistent throughout these similar type info blurts

**Comment by wodim** [comment]
I see your point but I think the wording is not appropriate for such a UI element. It reads like a tooltip, which it is not.

**Comment by un1versal** [comment]
The rationale behind this was party because we already had status labels for various other activities, like connecting, logging in etc... so it showed **server name:**  - logging in and other labels.

Also assuming you add other applets this ties in better with those which also have labels.

The only difference is here we cant turn this "applet" off afaik.

it seems more well rounded this way, because its something new it may seem more intrusive change. lets see how many people dislike it and for what reasons.

**Comment by un1versal** [comment]
Here is a suggestion... I look at a few different softwares and all have some sort of labels here.

So I could have a go at doing:

**[username +ugit] on server.name.blah**
