### ISSUE TITLE
Reconfiguring the server pane display? [question/enchancement?]

### ISSUE THREAD

**Issue by lepasserby** [kvirc/KVIrc#2036]
When connecting, the leftmost pane gives list of servers connected to
However, when one is connected to several accounts at same server it becomes uncomfy (a whole bunch of "freenodes" there, see screenshot)

![picer](https://cloud.githubusercontent.com/assets/7109762/16489598/ed24bb28-3ede-11e6-8d56-d68aadbe2fbe.jpg)

Any way to display something else, like, say, a custom account name or the note that one can configure for each server or... something ?
Am I missing some important UI part ?

P.S.:
Running 4.2.0 KVIrc

**Comment by Heufneutje** [comment]
The most logical thing to me would be the network and the nickname, since that combination should always be unique.

**Comment by lepasserby** [comment]
@Heufneutje 
makes sense, good idea!

Also, displaying the "description" could be useful.

Can it be done with current KVIrc via say a theme, or does this require a more in-depth modification  ?

**Comment by un1versal** [comment]
Via UI

1) Uncheck this box (general preferences > IRC or type 
2) Click apply.
3 Click OK

![capture](https://cloud.githubusercontent.com/assets/3521959/16494033/b3474398-3edf-11e6-8d6e-2aa422fae7d0.PNG)

Via command line

1) type `/option boolShowNetworkNameForConsoleWindowListEntry 0` on input line
2)  press enter
3) enjoy

Then you should ge the actual server name, not network name up there.

As long as the servers are always different, thats it.

aside from this, Im not aware of any way to change this easily, personally im not sure exactly how to do what Heufneutje suggested

**Comment by un1versal** [comment]
> The most logical thing to me would be the network and the nickname, since that combination should always be unique.

Lets say that you can display **network + nick**, thats a minimum width of 200 pixels on treelist to see both
**if classic list**, the buttons would also be 200 pixes **each** and you run out of space quickly and things start to disapear, 
thats 600 pixels wide (total) just for the network buttons, + add channels and queries, soon enough you wont read any of what it says there
Thats assuming its **network - nickname** (that size max) and what the screenshot there says.

**quick test** 
- conditions minimum 3 entries per network (combined queries+channels)
- test Desktop resolution 1650x1050

test 200 pixels wide treeview **(OK)** readable
![capture](https://cloud.githubusercontent.com/assets/3521959/16495986/a9a11e42-3ee7-11e6-8258-03987ef4cbd0.PNG)

Test 200 pixels wide button
![cap1](https://cloud.githubusercontent.com/assets/3521959/16495996/b4bdb394-3ee7-11e6-983a-ddaeb6c16374.PNG)

As you can see the classic list this feature would be unusable very quickly as the buttons
in fact it wont let the button go 200 pixels wide due to amount of entries.

The better idea is to alternatively display the description, but this is by default rather long. more than 200 pixels wide in most cases

also tested classic view with resolution of 1920x1080 and KVIrc at max width, buttons text is less than 200 pixels and already is unreadable

I see this as a edge case feature and as such the law of diminishing returns starts to play in my mind. especially given the outcome.

@lepasserby I'll happily set a feature request on here, but dont hold your breath we have better features waiting 10+ years for implementation.

**Comment by lepasserby** [comment]
@un1versal 
Thanks!
It's marginally more comfy without network name (at least server names ending up usually different) but still kind of crotchety. I guess I'll be using a different IRC client for a few of my "different freenode" accounts despite my principled love of KVIrc.
Accidentally sending a message from an alt can prove embarrassing at times :)

I think option allowing to display first N characters of description where N is a number KVIrc devs think is most UI friendly may be best.

People who need this kind of thing will just plan their descriptions accordingly :)

**Comment by un1versal** [comment]
there is a sort of botched work around

you can create 3 networks and name them so you end you with 3 different versions of freenode (or whatever) and name those networks to suit your purposes.

Then copy and paste the servers into those networks and add your login details to each network (not the servers)

done?

**Comment by lepasserby** [comment]
@un1versal 
Doesn't seem to work for me,
Created new network N
Created a server there with port details and hostname, but no login details
added username/password to network, not server
Clicked connect

Result:
still displays "freenode" or server's name, not the network's name

**Comment by un1versal** [comment]
~~:/ try adding details to server and check the box ON again `/option boolShowNetworkNameForConsoleWindowListEntry 1`~~

~~if that doesnt do it im out of ideas.~~

I thought it read the network name from the server dialog which clearly isnt the case... changing that however, is also not a good idea.

so the only thing for it is using server names...

**Comment by un1versal** [comment]
I dont think this would ever work, as is we already have problems with the network name length field when in classic view the right end fades away (depending) and the nickname would end up fading away just as well.

Using description relies on users changing defaults and copying networks/servers to do this and that is botch job to have as an option.

so youre stuck with server names, assuming that you lock each nick login to a specific server, you only have to remember not to use wrong server.

closing as wontfix, unless some magical being implements this in a way that wont cause those issues.

**Comment by un1versal** [comment]
There maybe a way around this that doesnt involve any server lists.... see https://github.com/kvirc/KVIrc/issues/2057

I realized some IRC clients show the current user nickname by input line

![capture](https://cloud.githubusercontent.com/assets/3521959/16708295/8f902afc-45e5-11e6-9945-e71da0e90a52.PNG)

If the nickname is visible in that area, this problem would be less likely to occur.

**Comment by lepasserby** [comment]
@un1versal Yeah, showing nick on input line would be a very okay way to go about it, IMHO
