### ISSUE TITLE
KviIrcView and KviInput don't take into account that a character can be more than 1 bytes long

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2051]
For example, if you copy this into the KviInput box:

> 𝔗𝔥𝔬𝔲 𝔰𝔥𝔞𝔩𝔱 𝔯𝔢𝔞𝔡 𝔱𝔥𝔢 𝔉𝔄𝔔

And then hit backspace, it turns into this:

![2016-07-07_19-47-18](https://cloud.githubusercontent.com/assets/1001553/16663231/ad3d4b0e-447b-11e6-896d-cdeb8d912a66.png)

Then if you hit backspace again (to remove the �) and then the left arrow, the cursor is positioned between both the two bytes the 𝔄 is composed of. If you type a letter, the 𝔄 is split in two:

![2016-07-07_19-47-30](https://cloud.githubusercontent.com/assets/1001553/16663290/de5a6262-447b-11e6-9117-82d86c5f930a.png)

Similar stuff happens to the KviIrcView when you try to select characters:

![2016-07-07_19-49-29](https://cloud.githubusercontent.com/assets/1001553/16663313/f45c6f9c-447b-11e6-8eb7-5148d7ed18e6.png)

The font metrics calculated for those letters are not of the letter themselves, but of the replacement characters. Example:

![2016-07-07_19-50-12](https://cloud.githubusercontent.com/assets/1001553/16663341/0a84c35a-447c-11e6-9634-335550cb3b74.png)

There's only one space there, but the KviIrcView is calculating the width of �����������������... etc

**Comment by un1versal** [comment]
[information required when making a bug report via github issues](https://github.com/kvirc/KVIrc/wiki/Submitting-a-bug-report#information-required-when-making-a-bug-report-via-github-issues)

**Comment by CyberShadow** [comment]
Reproducible with master (96e790b6a909681d5caf7b902db7402de3d5272f).

FWIW, `QChar` is 2 bytes long (UTF-16 / UCS-2 code unit), the problem is with characters outside the Unicode Basic Multilingual Plane. However, even if support for surrogate characters were to be implemented, there would still be the problem with combining marks and such. The correct solution would be iterating over Unicode graphemes (which can be more than one Unicode code point)...

**Comment by un1versal** [comment]
see https://github.com/kvirc/KVIrc/issues/1855#issuecomment-231227160

**Comment by wodim** [comment]
It's not the same bug.

**Comment by un1versal** [comment]
never said it was
