### ISSUE TITLE
CTCP actions to channels whose names contain '!' are mishandled.

### ISSUE THREAD

**Issue by AndrioCelos** [kvirc/KVIrc#2114]
### Expected behavior

The action would appear in the window of the channel to which it was addressed.
### Actual behavior

The action appeared in the active window with the message `The following CTCP ACTION has unrecognized target #Hi!`.
@un1versal noted that, in the case where the part of the channel name before the `!` was another channel that he was on, the action appeared in that channel instead.
This bug was not observed with other CTCP requests.
### Steps to reproduce the issue
1. Join a channel whose name contains a `!` character.
2. Have someone send a CTCP ACTION (`/me`) to the channel, or use `/inject` to simulate one.
### System information

Observed on:
- KVIrc 4.9.2 git:git-6942-g[66bf05d](https://github.com/kvirc/KVIrc/commit/66bf05daeadbef086bad47198bad6131aa1f2886) (built on 2016-08-17 06:36:49 UTC) on Windows 10
- KVIrc 4.9.2 git:git-6948-g[f5a9aa8](https://github.com/kvirc/KVIrc/commit/f5a9aa81e967cc2146ffe935ce873e9d6f4aa50c) (built on 2016-08-19 06:31:36 UTC) on Linux

**Comment by IceN9ne** [comment]
Bug introduced with commits f5d6aa3 and b1de770 by @CyberShadow for self-message.  I'd PR the fix, but I'm not sure how to address it without potentially breaking the "self-message" feature, since I'm not sure what that even is.

Bug is in this line:
https://github.com/kvirc/KVIrc/blob/master/src/kvirc/sparser/KviIrcServerParser_ctcp.cpp#L1442

`QString szWindow = bIsChannel || bSelfMessage ? szTargetNick : msg->pSource->nick();`

It's using `szTargetNick` (which strips the `!` and everything after it in the channel name) instead of `msg->szTarget` when it is `bIsChannel`.  If it is `bSelfMessage`, I'm not sure if it should be `msg->szTarget` or `szTargetNick` for that situation, so I'll leave it up to someone who knows better to make that decision so it can be fixed properly rather than a quick and dirty patch.

**Comment by AndrioCelos** [comment]
@IceN9ne, [`znc.in/self-message`](http://wiki.znc.in/Query_buffers#Self_messages) basically includes your own messages in query replays.

**Comment by un1versal** [comment]
CyberShadow is likely not going to be available to fix any of the issues caused by his PR's as fast as we would like (he like everyone else is extremely busy), only DarthGandalf off top of my head knows this stuff maybe he can suggest a quick fix that doesnt break anything.
