### ISSUE TITLE
add/improve support for CritenIRCd(a1)-1.4(05) channel modes

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2122]
reported via a KVIrc user in IRC confirmed by myself, marked as feature request since KVIrc supports Criten but idk if its the same (doesnt look like its same). In case its a bug please swap labels

![demo-ab](https://cloud.githubusercontent.com/assets/3521959/17967051/0b02fea2-6abd-11e6-911d-caf821c384a6.gif)
![capture](https://cloud.githubusercontent.com/assets/3521959/17967050/0b0131e4-6abd-11e6-9470-26f5c7d934dd.PNG)

 ### Expected behavior
no empty or unknown channel modes
### Actual behavior

channel modes `r` and `f` at least are empty and `q` shows as unknown

`CritenIRCd(a1)-1.4(05) supporting user modes 'oiws' and channel modes 'obtkmlvsn'
[09:40:31] This server supports: EXCEPTS=e CHANTYPES=#& PREFIX=(aohv)!@%+ CHANMODES=be,k,l,cimnpqstAKMNORS STATUSMSG=!@%+CASEMAPPING=ascii STD=i-d :are available on this server`
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-34-generic
System version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-24 05:52:18 UTC
Sources date: 20160823
Revision number: git-6951-g753a415
System name: Linux-4.4.0-34-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

**Comment by IceN9ne** [comment]
It would be helpful if you provided either a description of what `+q` did or a server that is running that IRCD version.

Edit: Nevermind, I see the network name in the ISUPPORT message you posted.

If you notice, `f` doesn't show up in the channel mode editor, which I assume is because it isn't listed in the ISUPPORT message.  Not sure if we can force that into the list or if we can only supply it in the tooltip.  I'd have to look at the code.

**Comment by un1versal** [comment]
fixed by https://github.com/kvirc/KVIrc/issues/2124
