### ISSUE TITLE
Runtime error: A popup menu can't be popped up twice

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#2140]
### Expected behavior

The popup menu opens without any error.
### Actual behavior

The popup menu opens and I see this:

```
[16 сент., 20:56:26] [KVS] Runtime error: A popup menu can't be popped up twice
[16 сент., 20:56:26] [KVS]   In script context "OnURLLinkPopupRequest::URL popup", Строка 1, около символа 1
```
### Steps to reproduce the issue
1. Right-click on any URL in channel output
### System information

```
KVIrc 4.9.2 'Aria'

Информация времени выполнения:
System name: Linux 4.6.2-zen+
System version: #2 ZEN SMP Sat Aug 6 22:42:50 IST 2016
Архитектура: x86_64
Qt version: 5.6.1
Qt theme: breeze

Информация о сборке:
Build date: 2016-09-16 19:49:15 UTC
Sources date: 20160102
Revision number: f4c8791288c05d1e5881968ca1dbae4c1f2ec080
System name: Linux-4.6.2-zen+
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -O2 -pipe -march=bdver2 -ggdb3 -fno-strict-aliasing 
Qt version: 5.6.1
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, KDE, Transparency, Phonon, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

Gentoo, KDE 5

**Comment by DarthGandalf** [comment]
Thanks, @IceN9ne 
Apparently, I had 2 handlers for `OnURLLinkPopupRequest`: `URLpopup` and `URLpopup_1`.
The last restoration of default script upon upgrade must have caused this. Somehow. What else could it be?

**Comment by un1versal** [comment]
https://github.com/kvirc/KVIrc/commit/f8f50bd6a787fdae7ce03cc36f97068399700d66 does not fix this it actually ensures this issue is repeated.

As explained, this issue is caused by having two event handlers that call same popup.

If you are a existing user you will already have a `OnURLLinkPopupRequest`event handler called `URL popup.`
When you upgrade Kvirc after https://github.com/kvirc/KVIrc/commit/f8f50bd6a787fdae7ce03cc36f97068399700d66 and restore your events you then have two `OnURLLinkPopupRequest`event handler called `URL popup` and `default` that will then trigger this issue https://github.com/kvirc/KVIrc/commit/f8f50bd6a787fdae7ce03cc36f97068399700d66 proposes to fix.

If you are also unlucky enough to have come across #1959 the `OnURLLinkPopupRequest`event handler called `URL popup` will become `URLpopup` and again as above you end up with two event handlers calling same popup.

vicious circle. Therefore this is far from _fixed_

**Comment by IceN9ne** [comment]
I agree with @DarthGandalf that the event name should be `default` instead of `URL popup` since it is the default script and should follow what appears to be a common standard of KVIrc's default scripts' naming convention.

However, addressing @un1versal's concerns about the duplication when restore default scripts is run, maybe we should add additional checks into the restore code to check for the previously named `URLpopup` and `URL popup` and remove them if it sees them (preserving enabled/disabled status on the newly replaced `default` script?).

Of course checking that their contents in the .kvc still match `Buffer=if($0%20!=%20"")%20popup.show%20channelpopup%20$0;` and giving a warning for the user to manually address the problem themselves if the contents have been changed manually by the user.

This should also be done for the `autoloadfish` script as well.

**Comment by un1versal** [comment]
![gif](https://cloud.githubusercontent.com/assets/3521959/18609140/a16ef714-7cf2-11e6-9df3-731f5a245f25.gif)

any event renamed will also have this issue like you say (fish or others), anyway my point is nothing was fixed, above gif after a upgrade / restore and you can even see #1959  in action.
