### ISSUE TITLE
CMake does not check for QSound

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2166]
When compiling current master, I got:

_/home/wodim/KVIrc/src/modules/snd/libkvisnd.cpp:37:18: fatal error: QSound: No such file or directory_

CMake does not check for the existence of this file, which should be inside qtmultimedia.

**Comment by wodim** [comment]
The same happens with QPrinter, QSqlQuery.

Maybe I'm wrong but shouldn't CMake abort in these cases?

**Comment by IceN9ne** [comment]
These are found by the following CMake lines

    find_package(Qt5Multimedia)
    find_package(Qt5PrintSupport)
    find_package(Qt5Sql)

It appears that it does nothing if they aren't found, so you could add the keyword `REQUIRED` and it _should_ error within CMake if they aren't found.

    find_package(Qt5Multimedia REQUIRED)
    find_package(Qt5PrintSupport REQUIRED)
    find_package(Qt5Sql REQUIRED)

As to whether this is the right thing to do when they aren't found, maybe they should have compilation locks and just not compile those objects that require them?

The QPrinter and QSqlQuery are just `KvsObject`s, so that would probably work for them pretty easily, but QSound is needed by the `snd` module.

**Comment by wodim** [comment]
Yes obviously `#define` is the way to go (why would an IRC client require you to have QPrinter?)

**Comment by wodim** [comment]
testing notifications

**Comment by wodim** [comment]
testing notifications
