### ISSUE TITLE
Add a checkbox to enable/disable handlers

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2189]
The way we show the status of event handlers stinks, I've seen #2188 happening one thousand times already. It's just an icon going grey... it's almost impossible to spot.

 I think there should be a checkbox for that. Something like this:

![2017-02-15_17-29-46](https://cloud.githubusercontent.com/assets/1001553/22984138/be8c2064-f3a4-11e6-8d36-a7125d51c310.png)

**Comment by Donat76** [comment]
The default option in KVIrc settings, also a checkbox, is to disable broken handlers. I ran into this several times when testing handlers and it took me a while to find out how to turn that option off and like you mentioned for the original issue... I didn't know handlers were being disabled automatically and the color difference wasn't obvious until I happened to notice.  Could the check boxes be placed in the list box on the left next to or replacing the <> next to the handler name.  And be able to click on the list box and expand the whole tree just to get a quick overview of what's checked rather then having to click on each handler to see the checkbox on the implementation screen to the right.  Also if a handler is disabled automatically, and maybe it already does this in a not so obvious way, can it popup a warning and or print it to the active console? Or even make the [ <> handler name]  RED for stopped / disabled or GREEN for active / enabled instead of grey.  Just red from grey would be a better signal.

**Comment by wodim** [comment]
You already get a warning in the current window/console when a handler gets disabled because it contains an error.

But I agree with making a change to the colour of the icons. Or maybe the checkbox would be enough?

**Comment by Donat76** [comment]
The red or green color change for the <> in front of the handler name should be sufficient in my opinion as a quick visual indicator. The right click mouse button menu would also need a red <> instead of grey. Also... The other scripting GUI menus in this subsection of KVIrc menus doesn't have check boxes unless it under the 'flags' tab to the right of 'code'.  But for one option that wouldn't make sense.  Some have buttons to the right of where the topmost text box is or would be and in this case could be a button with label 'Enable' that toggles to label 'Disable'.  This would keep some sort of GUI  consistency in this case. I agree that this comes up and I had to stumble through it too.  The color change should be enough and not change the GUI layout but a toggle button to the right of the upper most text box would look consistent.  What are your thoughts on this?  I've heard it said that the KVIrc GUI isn't too consistent but this section seems to be. Just my 2 cents. :)

**Comment by Donat76** [comment]
After looking at the icon file for the <>, it's not one solid color, has shading and shadowing. So it's not as easy to change as I originally thought.  A checkbox would be fine.  although it would be nice to have it in the tree view. Of course, whatever you decide to do is alright, I just wanted to throw some thoughts out there.

**Comment by wodim** [comment]
That's interesting, I hadn't considered it.

**Comment by Donat76** [comment]
I like the new icon. :) Shaded and everything.  Just curious what icon editor you used? I just snatched the new icon out of the repository and copied it directly into the coresmall directory. Looks good.  What is the optipng -o9 committ do?

**Comment by wodim** [comment]
I used GIMP, I took the green icon, put a dark red layer on top of it with a blending method. So I simply recoloured the green icon.

And optipng is a command that greatly reduces the size of a png file without losing quality.

**Comment by Donat76** [comment]
Hmmm...  I wonder why it didn't do all the PNG files.  It seems to have missed some in the kvirc /data /pics.  There may be others elsewhere but I noticed it right away while looking through GIT.  The GIT description is old for a few of the PNG files and just to be sure I checked the SHA-1 checksums and indeed, those PNGs were not changed for some reason.  Could OptiPNG just not be able to optimize them, so they were left the same and when you committed to GIT they wouldn't show with the new description for that reason?  

https://github.com/kvirc/KVIrc/tree/master/data/pics

**Comment by wodim** [comment]
optipng recompresses files to try and make them smaller, but some were already compressed enough, that's why they were not modified.

**Comment by Donat76** [comment]
Thank you and I hope I'm not annoying you with all the questions or comments.  I'm always trying to learn new things.  The new red icon stands out very well.  Hopefully people will know to right click on it but you already have to do that to add a new handler, unless it's added by a script. When I stumbled through this issue, my eyes glazed over the color difference and it was a "duh" moment when I saw it and finally realized why my handler wasn't working. This change should save some frustration.
