### ISSUE TITLE
Prioritize tab completion by last spoken order

### ISSUE THREAD

**Issue by staticfox** [kvirc/KVIrc#2216]
Requested by Ziginox on Rizon. Makes sense and doesn't seem too hard to do.

**Comment by AndrioCelos** [comment]
Looking through the code, I notice that the user lists are implemented as what appear to be doubly linked lists, and tab completion steps through that list until it reaches the last found nickname.
To do this, we'd need to keep a separate list, sorted by the last message timestamp (which [KVIrc already keeps track of](https://github.com/kvirc/KVIrc/blob/master/src/kvirc/ui/KviUserListView.h#L162)), or rebuild that list each time `Tab` is pressed.
I'd prefer the former solution...

**Comment by AndrioCelos** [comment]
Got the option added with [this commit](https://github.com/AndrioCelos/KVIrc/commit/cb1cd3a44e39e4485fc2b62971753cf7edc3d91c), but it's currently hidden. May I have help adding it to the options dialog?

**Comment by wodim** [comment]
You can look at another implementations of combo boxes. We don't have any of our "magic" combo boxes, but a very similar thing is implemented in `OptionsWidget_ircView.cpp`, where it is constructed and added to the layout:

https://github.com/AndrioCelos/KVIrc/blob/cb1cd3a44e39e4485fc2b62971753cf7edc3d91c/src/modules/options/OptionsWidget_ircView.cpp#L56-L58

Then the option is read and the combo box is given a value:

https://github.com/AndrioCelos/KVIrc/blob/cb1cd3a44e39e4485fc2b62971753cf7edc3d91c/src/modules/options/OptionsWidget_ircView.cpp#L85-L98

And here the value of the combo box is saved if the user clicks apply/ok (in your case the implementation will be simpler): 

https://github.com/AndrioCelos/KVIrc/blob/cb1cd3a44e39e4485fc2b62971753cf7edc3d91c/src/modules/options/OptionsWidget_ircView.cpp#L121-L134

**Comment by AndrioCelos** [comment]
I actually worked out the problem was KVIrc using the globally installed version of the options module, instead of the new one.
I appreciate your help, though, @wodim.

**Comment by pragmaware** [comment]
Currently the code in  #2242 has some bugs that need to be addressed.

- Users that leave the channel remain in the completion list. They should be removed.
- Users that change their nickname should be removed from the completion list
- The completion list is not properly cleared when a message is sent. When a different completion is requested the old one is re-proposed.
- A similar problem happens when one presses tab to perform one completion and then changes his mind, corrects the first letters in the line and then presses tab again.
