### ISSUE TITLE
Installation size

### ISSUE THREAD

**Issue by mdcclxv** [kvirc/KVIrc#2357]
115 MB for an IRC client?! What the .....?! You give a new meaning to bloatware.

**Comment by IceN9ne** [comment]
Well, it's 65MiB on my system (linux), but not all of that is loaded due to how modules work, and only what I need is actually loaded at run time.

32MiB of that is help documentation.
7.5MiB is translations.

I'm really failing to see how this is considered large.

I have a feeling you're a Windows user, so it's likely the extra space is consumed by Qt libraries needed to run your application, since Windows doesn't have a great facility for installing dependencies.

**Comment by ctrlaltca** [comment]
Closing as: trolololo
