### ISSUE TITLE
Stuff to fix on macOS

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2412]
* Every widget whose font size is stored in the config file (i.e. not controlled by the Qt theme) ends up with very small letters on macOS. A font size of 10 on Windows or Linux translates to 8 or so. Therefore the default IrcView/Input/UserList/ChannelList etc. widgets have tiny letters on every theme.

* The Finder window that opens when you mount the dmg file [looks terrible](https://user-images.githubusercontent.com/1001553/48954853-6f147f00-ef4b-11e8-8ef6-3d12675f505e.png).

* The size of the window list widget resets all the time, for example when you change between channels.

* The default Qt theme is _windows_.

* Still need a new indicator/systray/whatever black and white icon.

**Comment by v-ji** [comment]
To add to this: 

- Icons do not scale to retina displays and look pixelated

<img width="430" alt="combined" src="https://user-images.githubusercontent.com/1476338/78471429-85cb0880-7731-11ea-9e3a-b038fdc80f56.png">

**Comment by ctrlaltca** [comment]
We had recent fixed for both font styles (#2568), the DMG (#2556), and a general Qt version upgrade that could possibly fix macos-related problems.

We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
