### ISSUE TITLE
[bug] network/server vanishing from UI

### ISSUE THREAD

**Issue by ghost** [kvirc/KVIrc#2438]
* KVIrc 5.0.0 'Aria' (x64) portable mode
* Windows 10 Professional (x64) (Build 18362)
___
Adding new network/server via UI the data is being saved in serverdb.kvc but vanishes from the UI (and thus being inaccessible)

**Comment by AndrioCelos** [comment]
I notice that you haven't added any servers for your network. What you're seeing is a minor bug in the code that handles the favourites filter. Since you have no servers, no servers are shown by the filter, so it thinks the network should be hidden.

https://github.com/kvirc/KVIrc/blob/8db61929facd9bfed245752c538b51d0242c3e2e/src/modules/options/OptionsWidget_servers.cpp#L2091

If you edit the filter text box so that your empty network matches the filter, even making it empty again, all networks will be correctly shown.

**Comment by ghost** [comment]
Happens also with filter disabled. However, adding a server after network and only then pressing apply || ok the settings remain visible in the UI

**Comment by AndrioCelos** [comment]
There's a related bug whereby the favourites filter is not respected if you edit the text filter, and vice versa.
