### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by onkobu** [kvirc/KVIrc#2538]
[Gentoo Linux](https://bugs.gentoo.org/905955) is phasing out KVIrc:

* www.kvirc.net seems unmaintained, TLS certificate #2508 again/ still expired (2021)
* no release since 2019
* Gentoo builds snapshot from 2021
* dependency on app-text/enchant:0

Will be removed from the distro 08.06.2023. Time to get busy.

**Comment by DarthGandalf** [comment]
Thanks, I replied on gentoo-dev ML

**Comment by erwinc1** [comment]
It's still being worked on. Just make the binaries yourself :)

**Comment by abazaba855** [comment]
> It's still being worked on. Just make the binaries yourself :)

Are there any instructions available to build it for yourself on Windows (11) using MSYS2/MinGW-64 ?

**Comment by ctrlaltca** [comment]
@abazaba855 compiling using MinGW is supported but no up-to-date instructions are available.
Here's some instructions for MSVC you can adapt to MinGW: https://github.com/kvirc/KVIrc/wiki/Compiling-KVIrc-on-Windows
Here's the actual script used to create nighly builds: https://github.com/kvirc/KVIrc/blob/master/.appveyor.yml

**Comment by DarthGandalf** [comment]
@abazaba855 MSYS2 install should be trivial, and mostly the same as on Linux, because you can install all the dependencies from pacman.

MSVC setup requires LOTS of hacks for KVIrc, unlike MSYS2 setup. The reason why we use MSVC on CI instead of mingw is because installing all dependencies from pacman (especially, Qt) takes big chunk of the time budget, and the build is killed before finishing due to timeout of 1 hour. AppVeyor has MSVC version of Qt pre-installed, so I had to go with MSVC build there.

**Comment by abazaba855** [comment]
Hi,

I already looked at the MSVC instructions, and basically took that as a guide for installing all the needed dependencies. But I am getting build errors, and can't figure out if its because I am doing something wrong, there's something wrong with my setup, or if its just not possible at the moment. If someone is willing and able to look at it (and the errors I'm getting) with me and see if we can make it work, that would be nice. Otherwise, I think I am just going to stick with the latest build that is available over here: https://nightly.kvirc.net/ 

Thanks.

**Comment by ctrlaltca** [comment]
Feel free to post the logs, we'll take a look.
By the way, you can get new development snapshots from here: https://ci.appveyor.com/project/DarthGandalf/kvirc
Recent builds have a "artifacts" section where you can download the setup

**Comment by abazaba855** [comment]
Thanks. Just to make sure I am not doing things incorrectly, perhaps I should specify what I did :

Use the 'MSYS2 MSYS' icon/shortcut, and installed packages and updates with pacman.

Use the 'MSYS2 MinGW 64-bit' icon to launch a prompt.

$ git clone https://github.com/kvirc/kvirc.git
$ mkdir build
$ cd build
$ cmake ../kvirc -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=release -DWANT_KDE=0 "-DEnchant_FOUND=1" > ./cmake.log 2>&1
$ make > ./make.log 2>&1
$ gzip cmake.log
$ gzip make.log
[cmake.log.gz](https://github.com/kvirc/KVIrc/files/12883006/cmake.log.gz)
[make.log.gz](https://github.com/kvirc/KVIrc/files/12883009/make.log.gz)

**Comment by Dessa** [comment]
i don't have a msys setup here, but specifying Unix Makefiles will actually assume Unix in various ways, hence the breakage.
according to [this](https://www.msys2.org/docs/cmake/) you should use either Ninja (the msys2 default) "MSYS Makefiles" or "MingGW Makefiles"

**Comment by abazaba855** [comment]
I also get build errors when specifying 'MSYS Makefiles' and 'Ninja' for cmake (see attached logs), and "MinGW Makefiles" seems to be limited to 32-bit builds (and requiring 'mingw32-make') ? 
[cmake-msys-makefiles.log.gz](https://github.com/kvirc/KVIrc/files/12886202/cmake-msys-makefiles.log.gz)
[make-msys-makefiles.log.gz](https://github.com/kvirc/KVIrc/files/12886205/make-msys-makefiles.log.gz)
[cmake-ninja.log.gz](https://github.com/kvirc/KVIrc/files/12886207/cmake-ninja.log.gz)
[ninja-build.log.gz](https://github.com/kvirc/KVIrc/files/12886208/ninja-build.log.gz)

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
