### ISSUE TITLE
Is the latest version available on Linux/Debian for my Raspberry Pi 5?

### ISSUE THREAD

**Issue by Losing-My-Mind** [kvirc/KVIrc#2595]
Hi,
First of all, I'm not used to github so I didn't know if I could send a private message or send a message here.
I love so so soooo much KVIrc and I'm so grateful for your hard work and keeping up updated until today. It is by far my most favorite IRC Client.
The only little I would sayI miss is the hability to have the age/gender/city plugin witch makes men in blue color, women in pink color, and "others" in black color on bringht theme or white color on dark theme.
Also having the nicknames aligned on the right on a column , would make this already almost perfect IRC client just PERFECT.

<img width="1091" alt="kvircforshowing" src="https://github.com/kvirc/KVIrc/assets/137909687/243394c6-584e-4822-b227-6a7e4638b132">

I have one question. Is is possible to install KVIrc on my Raspberry Pi 5 which runs under linux debian ? Did I miss any documentation explaining it already.

Thank you for reading me and much much love for you because you're doing me happy with IRC and this software is really my favorite and much enjoyed. Cheers and best wishes for 2024 !

**Comment by ctrlaltca** [comment]
Hi, first thank you for your kind words.

The nickname sidebar has already been requested in https://github.com/kvirc/KVIrc/issues/2481, but unfortunately nobody picked up the job yet.

The idea of having different colors for nicknames based on the gender is something new; it surely will require some work, since there's no way to change the nick colors with the single exception of the "smart nick color" feature.

About your raspi5, kvirc should already be available there, even if a bit outdated: https://packages.debian.org/bookworm/kvirc
There's also an unofficial repository with more up-to-date versions, but it doesn't support arm CPUs: http://notesalexp.org/packages/
