### ISSUE TITLE
[Feature Request] Increase menu bar font size

### ISSUE THREAD

**Issue by githottub** [kvirc/KVIrc#2616]
My apologies if there's already a way to increase menu bar font size but I've checked the documentation section and Googled and not found any way to do so. It would also be helpful to increase the size of the icon bar immediately below it but, at the very least, being able to increase the size of the tiny text on the menu bar would help many people with less than perfect eyesight.

Thank you for your continued improvement of this great program and thanks for your consideration of this feature request.

**Comment by ctrlaltca** [comment]
Right now there's no setting that let you change the font size of the menubar / toolbar only.
There's a setting called "global application font" in "Settings -> Configure Theme -> General" that will change the global font used by the application, including the menubar and toolbar and all the other places where the default font is used.
This can be useful if the problem is caused by eg. a really high dpi screen with a large resolution.
Out of curiosity, what's your operating system / screen resolution?

**Comment by githottub** [comment]
Thanks for the reply. As it turns out, the tiny menu bar which had been a problem in versions 5.0 and 5.2, became larger immediately after updating just now to 5.2.2. So, anyone else experiencing this issue should also update if they haven't yet. But, as you indicated, changing the global font will also increase the size of the text in the menubar (and elsewhere). However, it doesn't help with increasing the size of the icons in the toolbars below it. Nevertheless, improving the text readability was the most important so, at least that can be accomplished and even fine tuned. Thanks again.

**Comment by ctrlaltca** [comment]
Thank you for your feedback. The 5.2.2 update included an updated version of the qt library, that fixes some long standing graphical issues.
