### ISSUE TITLE
upgraded to kvirc 5.2.4 quasar. right mouse menu not working in body of kvirc

### ISSUE THREAD

**Issue by ChasmanV** [kvirc/KVIrc#2646]
This is a bug report. My kvirc was updated in Ubuntu 22.04 and the right mouse menu stopped working in the main body of kvirc when I first launched it. When you click the right mouse button nothing happens. If in a channel it will work but not at first launch.

**Comment by ctrlaltca** [comment]
Sorry, I can't understand what exactly is the problem.
I get that the problem is about the popup menu not coming up when you right click on something.
Does it work on channels but not on console windows? 
Is it broken only the first time you click, and it works from the second time on?

Usually broken popups can be a consequence of broken scripts, can you try to:
 * scripting menu -> restore default script (if you have custom scripts, backup them before doing this)
 * try to run kvirc on a clean profile (a different user, or you can run `kvirc -f -n test.rc` from a shell)

**Comment by ChasmanV** [comment]
Sorry for the lack of detail. But yes in the console window the right mouse click does not work. I did try a different profile with the same result.  I don't have any custion scripts and will try the restore default script as well as kvirc -f -n test.rc to see and let you know.
Thank you for your help.

**Comment by ChasmanV** [comment]
ctrlaltca thank you. ran the restore default script and that resolved the issue. Thank you again.
