### ISSUE TITLE
Nickserv passwords with % characters don't work

### ISSUE THREAD

**Issue by cspiegel** [kvirc/KVIrc#2676]
Problem: NickServ passwords do not work when they contain a `%` character.

To reproduce: create a NickServ password with a percent sign in it, e.g. set the identify command to `msg NickServ IDENTIFY Nick 123%abc`

Connect to a server (which uses NickServ), and observe what is sent: `[PRIVMSG >>> NickServ] IDENTIFY Nick 123%`

It's cut off at the %, so it looks like the identify command is possibly being used directly as a format string somewhere.

**Comment by Ionic** [comment]
Variables are prefixed with a percent sign.

If you want to use a literal percent sign, escape it, such as in `123\%abc`.

The question, though, is, whether the identity command should be handled as a verbatim string or interpreted. There are arguments for either side, so...

**Comment by cspiegel** [comment]
Ah, I tried `%%` as if it were printf(), but didn't think of trying `\%`.  I guess it was surprising to me that it's not just a verbatim string, but that doesn't really mean much.  I'll close this issue since it's clearly working as intended, though perhaps it could be better documented in the dialog, e.g. in the tooltip.

Thanks for the quick response!

**Comment by Ionic** [comment]
The KVIrc Scripting Language (KVS) is ubiquitous in KVIrc, and this field is no exception. Users eventually stumble upon it, including its syntax, and once they have been bitten, it's quite natural.

Message input fields can be switched to "user-friendly mode", which disables KVS parsing, but not so much anything else.

This said, my initial thought that since the nickserv identification is mostly a password, it would make sense to treat it as a verbatim string instead of being interpreted as a command, but I've since found #2069 which tackles exactly that, and came to the conclusion that it's a command field in essence, so should be interpreted.
