### ISSUE TITLE
`boolUseCompositingForTransparency` is disabled in Qt6 Linux builds

### ISSUE THREAD

**Issue by alebastr** [kvirc/KVIrc#2686]
[`KviApplication::supportsCompositing()`](https://github.com/kvirc/KVIrc/blob/51f3abb83d6572f83f1721de340f28d09dd02c37/src/kvirc/kernel/KviApplication.cpp#L624) on Linux expects `COMPILE_QX11INFO_SUPPORT` to be set and returns false otherwise. Thus, Qt6 builds always assume that compositing is unsupported.

Not sure what's the best fix, but I suspect that simplifying `supportsCompositing()` to `return true` wouldn't upset a lot of people. I couldn't come up with a platform that can run Qt6 build of KVirc and is not Windows, Mac, Wayland or X11.

**Comment by ctrlaltca** [comment]
I agree, even KDE itself nowadays just returns true unless it's running on X11: https://invent.kde.org/plasma/breeze/-/blob/master/kstyle/breezehelper.cpp?ref_type=heads#L1825

**Comment by DarthGandalf** [comment]
KVIrc supports running on X11 too, not only Wayland though.

**Comment by ctrlaltca** [comment]
Since KVIrc 5 we were already always assuming `supportesComposing() == true` as long as QX11Info support was compiled in (I guess 100% of Linux builds).
This was caused by Qt5 missing the `QX11Info::isCompositingManagerRunning()` method at the time of porting (that was later reintroduced in Qt 5.7, but nobody cared).
The problem here is that Qt6 dropped QX11Info, so this is now always returning false on Linux even if most (all?) systems supports it. For the remaining 1%, they can still disable it from theme options -> transparency.
